import test from 'node:test';
import assert from 'node:assert/strict';
import bcrypt from 'bcryptjs';
import {PasswordResetService,hashResetToken,normalizeEmail} from '../lib/server/password-reset/service';
import type {Mailer,PasswordResetRepository,ResetToken,ResetUser} from '../lib/server/password-reset/types';

class Repo implements PasswordResetRepository {users:ResetUser[]=[];tokens:(ResetToken&{user:ResetUser})[]=[];password='old';sessions=1;async findUserByEmail(email:string){return this.users.find(u=>u.email===email)||null}async createToken(v:{userId:string;tokenHash:string;expiresAt:Date}){const user=this.users.find(u=>u.id===v.userId)!;this.tokens.push({id:String(this.tokens.length+1),...v,usedAt:null,user})}async findToken(hash:string){return this.tokens.find(t=>t.tokenHash===hash)||null}async completeReset(v:{tokenId:string;passwordHash:string;now:Date}){const t=this.tokens.find(x=>x.id===v.tokenId);if(!t||t.usedAt||t.expiresAt<=v.now)return false;t.usedAt=v.now;this.password=v.passwordHash;this.sessions=0;return true}}
class Mail implements Mailer {sent:{to:string;name:string;resetUrl:string}[]=[];async sendPasswordReset(v:{to:string;name:string;resetUrl:string}){this.sent.push(v)}}
const setup=()=>{const repo=new Repo(),mail=new Mail(),now=new Date('2026-08-12T00:00:00Z');repo.users.push({id:'u1',email:'active@example.com',name:'Active User',status:'Active'},{id:'u2',email:'disabled@example.com',name:'Disabled User',status:'Disabled'});return {repo,mail,service:new PasswordResetService(repo,mail,'https://app.example.com',()=>now),now}}
test('normalizes email and valid/unknown requests have no distinguishing return',async()=>{const x=setup();assert.equal(normalizeEmail(' ACTIVE@EXAMPLE.COM '),'active@example.com');assert.equal(await x.service.request(' ACTIVE@EXAMPLE.COM '),undefined);assert.equal(await x.service.request('unknown@example.com'),undefined);assert.equal(x.mail.sent.length,1)});
test('active user receives secure hashed token while disabled user receives none',async()=>{const x=setup();await x.service.request('active@example.com');await x.service.request('disabled@example.com');assert.equal(x.mail.sent.length,1);const raw=new URL(x.mail.sent[0].resetUrl).searchParams.get('token')!;assert.equal(x.repo.tokens[0].tokenHash,hashResetToken(raw));assert.ok(!JSON.stringify(x.repo.tokens).includes(raw));assert.equal(x.repo.tokens[0].expiresAt.getTime()-x.now.getTime(),30*60*1000)});
test('valid token resets password, revokes sessions, and is one-time',async()=>{const x=setup();await x.service.request('active@example.com');const raw=new URL(x.mail.sent[0].resetUrl).searchParams.get('token')!;assert.equal(await x.service.validate(raw),true);assert.deepEqual(await x.service.reset(raw,'new-password','new-password'),{ok:true});assert.equal(await bcrypt.compare('old',x.repo.password),false);assert.equal(await bcrypt.compare('new-password',x.repo.password),true);assert.equal(x.repo.sessions,0);assert.equal(await x.service.validate(raw),false);assert.equal((await x.service.reset(raw,'another-password','another-password')).ok,false)});
test('expired, short, mismatch, used, and disabled tokens are rejected',async()=>{const x=setup();await x.service.request('active@example.com');const raw=new URL(x.mail.sent[0].resetUrl).searchParams.get('token')!;assert.match((await x.service.reset(raw,'short','short')).error!,/minimal/);assert.match((await x.service.reset(raw,'password1','password2')).error!,/Konfirmasi/);x.repo.tokens[0].expiresAt=new Date(x.now.getTime()-1);assert.equal(await x.service.validate(raw),false);assert.equal((await x.service.reset(raw,'password1','password1')).ok,false);x.repo.tokens[0].expiresAt=new Date(x.now.getTime()+1);x.repo.tokens[0].user.status='Disabled';assert.equal(await x.service.validate(raw),false)});
test('mailer can be mocked without Microsoft credentials or credential leakage',async()=>{const x=setup();await x.service.request('active@example.com');const serialized=JSON.stringify(x.mail.sent);assert.ok(!serialized.includes('MICROSOFT_CLIENT_SECRET'));assert.equal(x.mail.sent[0].to,'active@example.com')});
