'use client';
import {useState} from 'react';
import {Plus,RotateCcw,UserX,X} from 'lucide-react';
import {actions,menuIds,type MenuId} from '@/lib/permissions';
import type {AppUser} from '@/lib/auth';
import type {Role} from '@/lib/schema';
import {useAuth} from './auth-provider';

const roles:Role[]=['Super Admin','Finance Manager','Accounting','Staff','Viewer'];
const labels:Record<string,string>={'laba-rugi':'Laba Rugi','arus-kas':'Arus Kas','ringkasan-budget':'Ringkasan Budget','budget-vs-actual':'Budget vs Actual','budget-department':'Budget per Department','budget-account':'Budget per Account','upload-budget':'Upload Budget','roles-permissions':'Roles & Permissions','chart-of-account':'Chart of Account','cost-center':'Cost Center','jurnal-umum':'Jurnal Umum','account-payable':'Account Payable','account-receivable':'Account Receivable','financial-report':'Financial Report','management-report':'Management Report','custom-report':'Custom Report'};
const emptyForm={name:'',email:'',role:'Staff' as Role,company:'PT Triple Egg',department:'Finance',costCenter:'CC-001',status:'Active' as AppUser['status']};

export function AdministrationPage({type}:{type:'users'|'roles'}){
 const auth=useAuth();
 const [editing,setEditing]=useState<AppUser|null>(null);
 const [adding,setAdding]=useState(false);
 const [form,setForm]=useState(emptyForm);
 const openAdd=()=>{setForm(emptyForm);setAdding(true)};
 const openEdit=(user:AppUser)=>{setForm({name:user.name,email:user.email,role:user.role,company:user.scope.companies[0]||'',department:user.scope.departments[0]||'',costCenter:user.scope.costCenters[0]||'',status:user.status});setEditing(user)};
 const save=()=>{
  const scope=form.role==='Super Admin'?{companies:[],departments:[],costCenters:[]}:{companies:form.company?[form.company]:[],departments:form.department?[form.department]:[],costCenters:form.costCenter?[form.costCenter]:[]};
  if(editing){auth.updateUser(editing.id,{name:form.name,email:form.email,role:form.role,status:form.status,scope});setEditing(null)}
  else{auth.addUser({id:crypto.randomUUID(),name:form.name,email:form.email,role:form.role,status:form.status,lastLogin:'Belum pernah login',scope});setAdding(false)}
 };
 return <><div className="flex items-center justify-between"><div><div className="label mb-2 text-blue-500">Administration / Access Control</div><h1 className="text-2xl font-bold">{type==='users'?'Users':'Roles & Permissions'}</h1><p className="mt-1 text-xs text-slate-500">{type==='users'?'Kelola pengguna, role, status, dan data scope.':'Atur permission per menu dan per action.'}</p></div>{type==='users'&&<button className="btn btn-primary" onClick={openAdd}><Plus size={14}/> Add User</button>}</div><div className="card mt-6 overflow-x-auto">{type==='users'?<table><thead><tr>{['Name','Email','Role','Company','Department','Cost Center','Status','Last Login','Action'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{auth.users.map(u=><tr key={u.id}><td className="font-semibold">{u.name}</td><td>{u.email}</td><td>{u.role}</td><td>{u.role==='Super Admin'?'All':u.scope.companies.join(', ')||'All'}</td><td>{u.role==='Super Admin'?'All':u.scope.departments.join(', ')||'All'}</td><td>{u.role==='Super Admin'?'All':u.scope.costCenters.join(', ')||'All'}</td><td><span className={u.status==='Active'?'text-emerald-400':'text-red-400'}>● {u.status}</span></td><td>{u.lastLogin}</td><td><div className="flex items-center gap-3"><button title="Edit User" className="text-blue-400 hover:text-blue-300" onClick={()=>openEdit(u)}>Edit</button><button title={u.status==='Active'?'Disable User':'Enable User'} className={u.status==='Active'?'text-red-400':'text-emerald-400'} onClick={()=>auth.disableUser(u.id)}><UserX size={14}/></button><button title="Reset Access" className="text-slate-400 hover:text-white" onClick={()=>auth.resetUserAccess(u.id)}><RotateCcw size={14}/></button></div></td></tr>)}</tbody></table>:<PermissionMatrix/>}</div>{(adding||editing)&&<UserModal form={form} setForm={setForm} onClose={()=>{setAdding(false);setEditing(null)}} onSave={save} title={editing?'Edit User':'Add User'}/>}</>}

function PermissionMatrix(){
 const auth=useAuth();
 const [role,setRole]=useState<Role>('Super Admin');
 return <div className="p-4"><div className="mb-4 flex flex-wrap gap-2">{roles.map(item=><button key={item} onClick={()=>setRole(item)} className={`btn ${role===item?'btn-primary':''}`}>{item}</button>)}</div><div className="mb-4 flex items-center justify-between gap-3"><p className="text-xs text-slate-400">Centang permission yang boleh dilakukan oleh role <b className="text-slate-200">{role}</b>. Perubahan langsung tersimpan di browser demo ini.</p><button className="btn" onClick={()=>auth.resetRolePermissions(role)}><RotateCcw size={14}/> Reset Preset</button></div><table><thead><tr><th>Menu</th>{actions.map(x=><th className="capitalize" key={x}>{x}</th>)}</tr></thead><tbody>{menuIds.map(menu=><tr key={menu}><td className="font-semibold capitalize">{labels[menu]||menu.replaceAll('-',' ')}</td>{actions.map(action=><td key={action}><input aria-label={`${menu} ${action}`} type="checkbox" checked={Boolean(auth.rolePermissions[role]?.[menu]?.[action])} onChange={e=>auth.setRolePermission(role,menu as MenuId,action,e.target.checked)} className="h-4 w-4 cursor-pointer accent-blue-600"/></td>)}</tr>)}</tbody></table></div>}

function UserModal({form,setForm,onClose,onSave,title}:{form:typeof emptyForm;setForm:React.Dispatch<React.SetStateAction<typeof emptyForm>>;onClose:()=>void;onSave:()=>void;title:string}){
 const field='field mt-1 w-full';
 return <><div className="fixed inset-0 z-[80] bg-black/70" onClick={onClose}/><div className="fixed left-1/2 top-1/2 z-[81] w-[94vw] max-w-xl -translate-x-1/2 -translate-y-1/2 rounded-xl border border-[#203047] bg-[#0d1928] p-5 shadow-2xl"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold">{title}</h2><button onClick={onClose}><X size={18}/></button></div><div className="grid gap-4 md:grid-cols-2"><label><span className="label">Name</span><input className={field} value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))}/></label><label><span className="label">Email</span><input className={field} value={form.email} onChange={e=>setForm(v=>({...v,email:e.target.value}))}/></label><label><span className="label">Role</span><select className={field} value={form.role} onChange={e=>setForm(v=>({...v,role:e.target.value as Role}))}>{roles.map(r=><option key={r}>{r}</option>)}</select></label><label><span className="label">Status</span><select className={field} value={form.status} onChange={e=>setForm(v=>({...v,status:e.target.value as AppUser['status']}))}><option>Active</option><option>Disabled</option></select></label><label><span className="label">Company</span><input className={field} disabled={form.role==='Super Admin'} value={form.role==='Super Admin'?'All':form.company} onChange={e=>setForm(v=>({...v,company:e.target.value}))}/></label><label><span className="label">Department</span><input className={field} disabled={form.role==='Super Admin'} value={form.role==='Super Admin'?'All':form.department} onChange={e=>setForm(v=>({...v,department:e.target.value}))}/></label><label className="md:col-span-2"><span className="label">Cost Center</span><input className={field} disabled={form.role==='Super Admin'} value={form.role==='Super Admin'?'All':form.costCenter} onChange={e=>setForm(v=>({...v,costCenter:e.target.value}))}/></label></div><div className="mt-5 flex justify-end gap-2"><button className="btn" onClick={onClose}>Cancel</button><button className="btn btn-primary" disabled={!form.name||!form.email} onClick={onSave}>Save Changes</button></div></div></>;
}
