'use client';
import {Plus,RotateCcw,UserX} from 'lucide-react';
import {actions,defaultRolePermissions,menuIds} from '@/lib/permissions';
import type {Role} from '@/lib/schema';
import {demoUsers} from './auth-provider';
const roles:Role[]=['Super Admin','Finance Manager','Accounting','Staff','Viewer'];
const labels:Record<string,string>={'laba-rugi':'Laba Rugi','arus-kas':'Arus Kas','ringkasan-budget':'Ringkasan Budget','roles-permissions':'Roles & Permissions'};
export function AdministrationPage({type}:{type:'users'|'roles'}){return <><div className="flex items-center justify-between"><div><div className="label mb-2 text-blue-500">Administration / Access Control</div><h1 className="text-2xl font-bold">{type==='users'?'Users':'Roles & Permissions'}</h1><p className="mt-1 text-xs text-slate-500">{type==='users'?'Kelola pengguna, role, status, dan data scope.':'Atur permission per menu dan per action.'}</p></div>{type==='users'&&<button className="btn btn-primary"><Plus size={14}/> Add User</button>}</div><div className="card mt-6 overflow-x-auto">{type==='users'?<table><thead><tr>{['Name','Email','Role','Company','Department','Cost Center','Status','Last Login','Action'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{demoUsers.map(u=><tr key={u.id}><td className="font-semibold">{u.name}</td><td>{u.email}</td><td>{u.role}</td><td>{u.role==='Super Admin'?'All':u.scope.companies.join(', ')}</td><td>{u.role==='Super Admin'?'All':u.scope.departments.join(', ')}</td><td>{u.role==='Super Admin'?'All':u.scope.costCenters.join(', ')}</td><td><span className="text-emerald-400">● {u.status}</span></td><td>{u.lastLogin}</td><td><div className="flex gap-2"><button title="Edit User" className="text-blue-400">Edit</button><button title="Disable User" className="text-red-400"><UserX size={14}/></button><button title="Reset Access"><RotateCcw size={14}/></button></div></td></tr>)}</tbody></table>:<PermissionMatrix/>}</div></>}
function PermissionMatrix(){return <div className="p-4"><div className="mb-4 flex flex-wrap gap-2">{roles.map((role,i)=><button key={role} className={`btn ${i===0?'btn-primary':''}`}>{role}</button>)}</div><p className="mb-3 text-xs text-slate-400">Preset Super Admin — perubahan checkbox siap disimpan sebagai role_permissions di backend.</p><table><thead><tr><th>Menu</th>{actions.map(x=><th className="capitalize" key={x}>{x}</th>)}</tr></thead><tbody>{menuIds.map(menu=><tr key={menu}><td className="font-semibold capitalize">{labels[menu]||menu.replaceAll('-',' ')}</td>{actions.map(action=><td key={action}><input aria-label={`${menu} ${action}`} type="checkbox" defaultChecked={Boolean(defaultRolePermissions['Super Admin'][menu]?.[action])} className="h-4 w-4 accent-blue-600"/></td>)}</tr>)}</tbody></table></div>}
