'use client';
import Link from 'next/link';
import Image from 'next/image';
import {Eye,EyeOff,LockKeyhole,Mail} from 'lucide-react';
import {FormEvent,useEffect,useState} from 'react';

export function AuthFrame({children,title,subtitle}:{children:React.ReactNode;title:string;subtitle:string}){return <main className="min-h-screen grid place-items-center px-4 bg-[radial-gradient(circle_at_top,#17325a,#07111f_55%)]"><section className="card w-full max-w-md p-7"><div className="flex items-center gap-3 mb-6"><Image src="/triple-egg-logo.svg" alt="Triple Egg" width={48} height={48}/><div><strong className="text-lg">Triple Egg</strong><div className="text-xs muted">Financial &amp; Accounting</div></div></div><h1 className="text-2xl font-bold">{title}</h1><p className="muted text-sm mt-1 mb-6">{subtitle}</p>{children}</section></main>}
export function ForgotPasswordForm(){const [email,setEmail]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(false);async function submit(e:FormEvent){e.preventDefault();setLoading(true);try{const r=await fetch('/api/auth/forgot-password',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email})});const data=await r.json();setMessage(data.message)}finally{setLoading(false)}}return <form onSubmit={submit} className="space-y-4"><label className="block"><span className="label">Email</span><div className="relative mt-2"><Mail className="absolute left-3 top-3 text-slate-500" size={16}/><input className="field w-full pl-10" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="nama@perusahaan.com"/></div></label>{message&&<div role="status" className="rounded-lg border border-blue-700/50 bg-blue-950/40 p-3 text-sm text-blue-100">{message}</div>}<button disabled={loading} className="btn btn-primary w-full" type="submit">{loading?'Mengirim…':'Kirim Instruksi Reset'}</button><Link className="btn w-full" href="/login">Kembali ke Login</Link></form>}
export function ResetPasswordForm({token}:{token:string}){const [password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[show,setShow]=useState(false),[valid,setValid]=useState<boolean|null>(null),[error,setError]=useState(''),[success,setSuccess]=useState(false);useEffect(()=>{fetch(`/api/auth/reset-password?token=${encodeURIComponent(token)}`).then(r=>r.json()).then(v=>setValid(Boolean(v.valid))).catch(()=>setValid(false))},[token]);async function submit(e:FormEvent){e.preventDefault();setError('');const r=await fetch('/api/auth/reset-password',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token,password,confirmation})});const data=await r.json();if(r.ok)setSuccess(true);else setError(data.error)}if(valid===null)return <p className="muted">Memeriksa link…</p>;if(!valid&&!success)return <InvalidReset/>;if(success)return <div className="space-y-4"><div className="rounded-lg border border-emerald-700 bg-emerald-950/40 p-3 text-emerald-100">Password berhasil diperbarui.</div><Link className="btn btn-primary w-full" href="/login">Kembali ke Login</Link></div>;return <form onSubmit={submit} className="space-y-4"><PasswordField label="Password Baru" value={password} onChange={setPassword} show={show} toggle={()=>setShow(!show)}/><PasswordField label="Konfirmasi Password Baru" value={confirmation} onChange={setConfirmation} show={show} toggle={()=>setShow(!show)}/>{error&&<div role="alert" className="rounded-lg border border-red-800 bg-red-950/40 p-3 text-sm text-red-100">{error}</div>}<button className="btn btn-primary w-full">Reset Password</button></form>}
function PasswordField({label,value,onChange,show,toggle}:{label:string;value:string;onChange:(v:string)=>void;show:boolean;toggle:()=>void}){return <label className="block"><span className="label">{label}</span><div className="relative mt-2"><LockKeyhole className="absolute left-3 top-3 text-slate-500" size={16}/><input className="field w-full px-10" type={show?'text':'password'} minLength={8} required autoComplete="new-password" value={value} onChange={e=>onChange(e.target.value)}/><button aria-label={show?'Sembunyikan password':'Tampilkan password'} type="button" onClick={toggle} className="absolute right-3 top-2.5 text-slate-400">{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>}
function InvalidReset(){return <div className="space-y-4"><div role="alert" className="rounded-lg border border-red-800 bg-red-950/40 p-3 text-sm text-red-100">Link reset password tidak valid atau sudah kedaluwarsa.</div><Link className="btn btn-primary w-full" href="/forgot-password">Kirim ulang instruksi reset</Link></div>}
