'use client';

import {useMemo,useState} from 'react';
import {ArrowUpDown,CheckCircle2,Search,TriangleAlert,WalletCards} from 'lucide-react';
import {Bar,BarChart,CartesianGrid,Legend,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {applyFilters,useFinancial} from '@/lib/financial-store';
import type {BudgetRecord,FinancialTransaction} from '@/lib/schema';

const money=(value:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(value);
const actualValue=(row:FinancialTransaction)=>['liability','equity','revenue','payable'].includes(row.account_type)?row.credit-row.debit:row.debit-row.credit;
const pct=(actual:number,budget:number)=>budget?actual/budget*100:0;
const status=(budget:number,actual:number)=>actual>budget?'Over Budget':actual<budget?'Under Budget':'On Track';
const statusClass=(value:string)=>value==='Over Budget'?'bg-red-500/10 text-red-400':value==='Under Budget'?'bg-blue-500/10 text-blue-300':'bg-emerald-500/10 text-emerald-400';

type ReportRow={key:string;code:string;name:string;category:string;department:string;budget:number;actual:number;variance:number;percentage:number;status:string};
function useBudgetRows(){
  const {budgets,transactions,filters}=useFinancial();
  return useMemo(()=>{
    const selected=applyFilters(budgets,filters), actuals=applyFilters(transactions,filters);
    return selected.map(item=>({...item,actual:actuals.filter(row=>row.account_code===item.account_code&&(item.department_id==='Semua Department'||row.department_id===item.department_id)&&(item.cost_center_id==='Semua Cost Center'||row.cost_center_id===item.cost_center_id)).reduce((sum,row)=>sum+actualValue(row),0)}));
  },[budgets,transactions,filters]);
}
function grouped(rows:Array<BudgetRecord&{actual:number}>,key:(row:BudgetRecord)=>string):ReportRow[]{
  const map=new Map<string,ReportRow>();
  rows.forEach(row=>{const id=key(row), current=map.get(id)||{key:id,code:row.account_code,name:row.account_name,category:row.category||'Lain-lain',department:row.department_id,budget:0,actual:0,variance:0,percentage:0,status:'On Track'};current.budget+=row.budget;current.actual+=row.actual;map.set(id,current)});
  return Array.from(map.values()).map(row=>({...row,variance:row.budget-row.actual,percentage:pct(row.actual,row.budget),status:status(row.budget,row.actual)}));
}
function NoData(){return <div className="rounded-xl border border-blue-500/20 bg-blue-500/5 px-4 py-3 text-xs text-slate-400"><b className="text-slate-200">Belum ada data Budget.</b> Struktur laporan tetap ditampilkan dengan seluruh nilai awal Rp 0.</div>}
function KPI({label,value,percentage=false,text}:{label:string;value?:number;percentage?:boolean;text?:string}){return <div className="card p-4"><div className="flex justify-between"><span className="label">{label}</span><WalletCards size={16} className="text-blue-400"/></div><div className="mt-3 text-lg font-bold tabular-nums">{text??(percentage?`${(value||0).toFixed(1)}%`:money(value||0))}</div><div className="mt-2 text-[10px] text-slate-500">Berdasarkan filter terpilih</div></div>}
function Status({value}:{value:string}){return <span className={`${statusClass(value)} inline-flex rounded-full px-2.5 py-1 text-[10px] font-semibold`}>{value}</span>}
function ChartPanel({data,title='Ringkasan Budget vs Actual'}:{data:{name:string;budget:number;actual:number}[];title?:string}){return <div className="card p-5"><h3 className="text-sm font-semibold">{title}</h3><p className="mt-1 text-[10px] text-slate-500">Perbandingan nilai budget dan realisasi terfilter.</p>{data.length?<ResponsiveContainer width="100%" height={280}><BarChart data={data} margin={{top:25,right:10,left:5,bottom:5}}><CartesianGrid stroke="#203047"/><XAxis dataKey="name" stroke="#718198" fontSize={10}/><YAxis stroke="#718198" fontSize={10}/><Legend/><Tooltip contentStyle={{background:'#0b1726',border:'1px solid #203047',borderRadius:8}} formatter={(v:number)=>money(v)}/><Bar dataKey="budget" name="Budget" fill="#3b82f6" radius={[4,4,0,0]}/><Bar dataKey="actual" name="Actual" fill="#10b981" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer>:<div className="mt-5 flex h-[250px] items-center justify-center rounded-lg border border-dashed border-[#2a3b53] text-xs text-slate-500">Belum ada data Budget</div>}</div>}
function Table({rows,mode,searchable=false,varianceLabel='Variance'}:{rows:ReportRow[];mode:'account'|'department';searchable?:boolean;varianceLabel?:string}){const [query,setQuery]=useState(''),[sort,setSort]=useState<'code'|'name'|'budget'|'actual'>('code'),[asc,setAsc]=useState(true);const shown=rows.filter(row=>`${row.code} ${row.name} ${row.category} ${row.department}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>{const av=a[sort],bv=b[sort];return (typeof av==='number'?av-Number(bv):String(av).localeCompare(String(bv)))*(asc?1:-1)});const change=(key:typeof sort)=>{if(sort===key)setAsc(!asc);else{setSort(key);setAsc(true)}};return <div className="card overflow-hidden">{searchable&&<div className="border-b border-[#203047] p-4"><label className="relative block max-w-sm"><Search size={14} className="absolute left-3 top-3 text-slate-500"/><input className="field w-full pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari kode, biaya, atau kategori..."/></label></div>}<div className="overflow-x-auto"><table><thead><tr>{mode==='department'?<th>Department</th>:<><SortHead label="Kode Akun" onClick={()=>change('code')}/><SortHead label="Nama Biaya" onClick={()=>change('name')}/>{searchable&&<th>Kategori</th>}</>}<SortHead label="Budget" onClick={()=>change('budget')}/><SortHead label="Actual" onClick={()=>change('actual')}/><th>{varianceLabel}</th><th>%</th><th>Status</th></tr></thead><tbody>{shown.length?shown.map(row=><tr key={row.key}><td className="font-semibold text-slate-200">{mode==='department'?row.department:row.code}</td>{mode==='account'&&<td>{row.name}</td>}{searchable&&<td>{row.category}</td>}<td className="tabular-nums">{money(row.budget)}</td><td className="tabular-nums">{money(row.actual)}</td><td className={`tabular-nums ${row.variance<0?'text-red-400':'text-emerald-400'}`}>{money(row.variance)}</td><td>{row.percentage.toFixed(1)}%</td><td><Status value={row.status}/></td></tr>):<tr><td colSpan={searchable?8:mode==='department'?6:7} className="py-12 text-center text-slate-500">Belum ada data Budget</td></tr>}</tbody></table></div></div>}
function SortHead({label,onClick}:{label:string;onClick:()=>void}){return <th><button className="flex items-center gap-1 uppercase" onClick={onClick}>{label}<ArrowUpDown size={11}/></button></th>}

export function BudgetReport({type}:{type:'summary'|'comparison'|'department'|'account'|'remaining'}){const source=useBudgetRows(), accounts=grouped(source,row=>`${row.account_code}|${row.account_name}|${row.category}`), departments=grouped(source,row=>row.department_id);const rows=type==='department'?departments:accounts,totalBudget=rows.reduce((n,row)=>n+row.budget,0),totalActual=rows.reduce((n,row)=>n+row.actual,0),variance=totalBudget-totalActual,over=rows.filter(row=>row.status==='Over Budget').length,percentage=pct(totalActual,totalBudget);const chartRows=(type==='department'?departments:accounts).slice(0,10).map(row=>({name:type==='department'?row.department:row.name,budget:row.budget,actual:row.actual}));if(type==='summary'){const categories=grouped(source,row=>row.category||'Lain-lain');return <div className="space-y-5">{!source.length&&<NoData/>}<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><KPI label="Total Budget" value={totalBudget}/><KPI label="Total Actual" value={totalActual}/><KPI label="Sisa Budget" value={variance}/><KPI label="Variance" value={variance}/><KPI label="% Realisasi" value={percentage} percentage/><KPI label="Status Budget" text={over?'Perlu Perhatian':'On Track'}/></div><div className="grid gap-4 xl:grid-cols-2"><ChartPanel data={categories.map(row=>({name:row.category,budget:row.budget,actual:row.actual}))}/><Table rows={categories} mode="account"/></div></div>}
  if(type==='remaining'){const available=accounts.filter(row=>row.variance>0),used=accounts.filter(row=>row.variance<=0);return <div className="space-y-5">{!source.length&&<NoData/>}<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><KPI label="Total Budget" value={totalBudget}/><KPI label="Total Actual" value={totalActual}/><KPI label="Total Sisa Budget" value={variance}/><KPI label="% Pemakaian" value={percentage} percentage/><KPI label="Biaya Tanpa Sisa" text={String(used.length)}/></div><ChartPanel data={accounts.slice(0,10).map(row=>({name:row.name,budget:row.budget,actual:row.actual}))} title="Sisa Budget per Biaya"/><div><div className="mb-3 flex items-center gap-2"><CheckCircle2 size={16} className="text-emerald-400"/><h2 className="text-sm font-semibold">Rincian Sisa Budget</h2>{used.length>0&&<TriangleAlert size={15} className="text-amber-400"/>}</div><Table rows={[...available,...used]} mode="account" searchable varianceLabel="Sisa Budget"/></div></div>}
  const comparison=type==='comparison';return <div className="space-y-5">{!source.length&&<NoData/>}<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{comparison?<><KPI label="Total Budget" value={totalBudget}/><KPI label="Total Actual" value={totalActual}/><KPI label="Variance" value={variance}/><KPI label="% Pemakaian" value={percentage} percentage/><KPI label="Over Budget" text={`${over} Biaya`}/></>:<><KPI label={type==='department'?'Jumlah Department':'Jumlah Biaya'} text={String(rows.length)}/><KPI label="Total Budget" value={totalBudget}/><KPI label="Total Actual" value={totalActual}/><KPI label="Sisa Budget" value={variance}/><KPI label={`${type==='department'?'Department':'Biaya'} Over Budget`} text={String(over)}/></>}</div><ChartPanel data={chartRows} title={type==='department'?'Budget per Department':'Budget vs Actual'}/><div><div className="mb-3 flex items-center gap-2"><CheckCircle2 size={16} className="text-emerald-400"/><h2 className="text-sm font-semibold">{type==='department'?'Breakdown Department':'Rincian Budget per Biaya'}</h2>{over>0&&<TriangleAlert size={15} className="text-amber-400"/>}</div><Table rows={rows} mode={type==='department'?'department':'account'} searchable={type==='account'}/></div></div>}
