'use client';
import {useMemo} from 'react';import {Bot,Building2,ChartNoAxesCombined,Boxes,CircleDollarSign,HandCoins,Landmark,ReceiptText,Scale,TrendingUp,Wallet} from 'lucide-react';import {Bar,BarChart,CartesianGrid,Legend,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';import {applyFilters,monthNames,useFinancial} from '@/lib/financial-store';import type {AccountType,DashboardFilters,FinancialTransaction} from '@/lib/schema';
const rupiah=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
const balance=(r:FinancialTransaction)=>['liability','equity','revenue','payable'].includes(r.account_type)?r.credit-r.debit:r.debit-r.credit;
export function useDashboardData(){const store=useFinancial();const filtered=useMemo(()=>applyFilters(store.transactions,store.filters),[store.transactions,store.filters]);const balanceRows=filtered.filter(x=>x.statement_type==='balance-sheet');const incomeRows=filtered.filter(x=>x.statement_type==='income-statement');const legacy=filtered.filter(x=>!x.statement_type||x.statement_type==='journal');const bs=balanceRows.length?balanceRows:legacy;const pl=incomeRows.length?incomeRows:legacy;const sum=(rows:FinancialTransaction[],types:AccountType[])=>rows.filter(x=>types.includes(x.account_type)).reduce((n,x)=>n+balance(x),0);const asset=sum(bs,['asset','cash','receivable','inventory']),liability=sum(bs,['liability','payable']),revenue=sum(pl,['revenue']),expense=sum(pl,['expense']);return {store,rows:filtered,incomeRows:pl,kpis:[['Total Aset',asset,Building2],['Total Liabilitas',liability,Scale],['Total Ekuitas',sum(bs,['equity']),Landmark],['Pendapatan',revenue,TrendingUp],['Beban',expense,ReceiptText],['Laba Bersih',revenue-expense,ChartNoAxesCombined],['Kas & Bank',sum(bs,['cash']),Wallet],['Piutang',sum(bs,['receivable']),HandCoins],['Persediaan',sum(bs,['inventory']),Boxes],['Hutang Usaha',sum(bs,['payable']),CircleDollarSign]] as const}}
const unique=(a:string[])=>Array.from(new Set(a.filter(Boolean))).sort();
export function FilterBar(){const {transactions,budgets,filters,setFilters}=useFinancial();const filterRows=[...transactions,...budgets];const update=(key:keyof DashboardFilters,value:string)=>setFilters({...filters,[key]:value});const fields:[string,keyof DashboardFilters,[string,string][]][]=[['Periode','period',[['all','Semua Periode'],...unique(filterRows.map(x=>x.period)).map(x=>[x,x] as [string,string])]],['Bulan','month',[['all','Semua Bulan'],...monthNames.map((x,i)=>[String(i+1),x] as [string,string])]],['Tahun','year',[['all','Semua Tahun'],...unique(filterRows.map(x=>String(x.year))).map(x=>[x,x] as [string,string])]],['Company','company_id',[['all','Semua Perusahaan'],...unique(filterRows.map(x=>x.company_id)).map(x=>[x,x] as [string,string])]],['Department','department_id',[['all','Semua Department'],...unique(filterRows.map(x=>x.department_id)).map(x=>[x,x] as [string,string])]],['Cost Center','cost_center_id',[['all','Semua Cost Center'],...unique(filterRows.map(x=>x.cost_center_id)).map(x=>[x,x] as [string,string])]]];return <div className="card grid grid-cols-2 gap-3 p-4 md:grid-cols-3 xl:grid-cols-6">{fields.map(([label,key,options])=><label key={key}><span className="label">{label}</span><select value={filters[key]} onChange={e=>update(key,e.target.value)} className="field mt-1 w-full">{options.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>)}</div>}
export function KPIGrid(){const {kpis}=useDashboardData();return <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-5">{kpis.map(([title,value,Icon])=><div key={title} className="card p-4"><div className="flex items-start justify-between"><div className="label">{title}</div><div className="rounded-lg bg-emerald-500/10 p-2 text-emerald-400"><Icon size={16}/></div></div><div className="mt-3 text-lg font-bold">{rupiah(value)}</div><div className="mt-2 text-[10px] text-slate-500">{value===0?'Belum ada data':'Berdasarkan laporan terfilter'}</div></div>)}</div>}
const tt={contentStyle:{background:'#0b1726',border:'1px solid #203047',borderRadius:8,fontSize:11}};
export function Charts(){const {incomeRows}=useDashboardData();const data=monthNames.map((month,i)=>{const m=incomeRows.filter(x=>x.month===i+1);const income=m.filter(x=>x.account_type==='revenue').reduce((n,x)=>n+balance(x),0);const expense=m.filter(x=>x.account_type==='expense').reduce((n,x)=>n+balance(x),0);return {month,income,expense,profit:income-expense}}).filter(x=>x.income||x.expense);if(!data.length)return <div className="grid gap-4 xl:grid-cols-2">{['Trend Pendapatan vs Beban','Laba Bersih per Bulan','Komposisi Aset','Budget vs Actual'].map(x=><Chart title={x} key={x}><Empty/></Chart>)}</div>;return <div className="grid gap-4 xl:grid-cols-2"><Chart title="Trend Pendapatan vs Beban"><ResponsiveContainer width="100%" height={240}><LineChart data={data}><CartesianGrid stroke="#203047"/><XAxis dataKey="month" stroke="#64748b"/><YAxis stroke="#64748b"/><Tooltip {...tt}/><Legend/><Line dataKey="income" name="Pendapatan" stroke="#3b82f6"/><Line dataKey="expense" name="Beban" stroke="#f59e0b"/></LineChart></ResponsiveContainer></Chart><Chart title="Laba Bersih per Bulan"><ResponsiveContainer width="100%" height={240}><BarChart data={data}><CartesianGrid stroke="#203047"/><XAxis dataKey="month" stroke="#64748b"/><YAxis stroke="#64748b"/><Tooltip {...tt}/><Bar dataKey="profit" name="Laba Bersih" fill="#2563eb"/></BarChart></ResponsiveContainer></Chart><Chart title="Komposisi Aset"><Empty text="Komposisi aset mengikuti laporan Neraca terupload."/></Chart><Chart title="Budget vs Actual"><Empty text="Belum ada data budget untuk periode ini."/></Chart></div>}
function Empty({text='Belum ada data untuk periode ini.'}:{text?:string}){return <div className="flex h-60 items-center justify-center rounded-lg border border-dashed border-[#2a3b53] text-center text-xs text-slate-500">{text}</div>}
function Chart({title,children}:{title:string;children:React.ReactNode}){return <div className="card p-5"><h3 className="mb-5 text-sm font-semibold">{title}</h3>{children}</div>}
export function Insights(){const {rows}=useDashboardData();return <div className="card p-5"><div className="flex items-center gap-2"><div className="rounded-lg bg-blue-500/10 p-2 text-blue-400"><Bot size={17}/></div><div><h3 className="text-sm font-semibold">Analisa Otomatis</h3><p className="text-[10px] text-slate-500">Insight berdasarkan laporan periode terpilih</p></div></div><div className="mt-4 rounded-lg border border-dashed border-[#2a3b53] p-5 text-center text-xs text-slate-400">{rows.length?'Analisa dihitung dari Neraca dan Laba Rugi yang sedang ditampilkan.':'Belum ada data yang cukup. Upload Neraca dan/atau Laba Rugi.'}</div></div>}
