'use client';
import {useMemo,useState} from 'react';
import {RefreshCw} from 'lucide-react';
import {monthNames,useFinancial,applyFilters} from '@/lib/financial-store';
import {calculateCashFlow,calculateNeraca,customThreeMonthRange,transactionBalance,type ReportMonth} from '@/lib/financial-report-data';
import type {DashboardFilters,FinancialTransaction} from '@/lib/schema';
import {CashFlowReport,NeracaReport} from './financial-reports';

const money=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
type Selection={mode:'quarterly'|'custom';months:ReportMonth[];label:string};
function PeriodControls({onApply}:{onApply:(selection:Selection|null)=>void}){
 const {transactions,filters}=useFinancial(),yearsAvailable=Array.from(new Set(transactions.map(row=>row.year))).sort((a,b)=>b-a),initialYear=filters.year==='all'?(yearsAvailable[0]||new Date().getFullYear()):Number(filters.year),initialMonth=filters.month==='all'?1:Number(filters.month);
 const [mode,setMode]=useState<'single'|'quarterly'|'custom'>('single'),[year,setYear]=useState(initialYear),[quarter,setQuarter]=useState<1|2|3|4>(Math.ceil(initialMonth/3) as 1|2|3|4),[start,setStart]=useState<ReportMonth>({month:initialMonth,year:initialYear}),[end,setEnd]=useState<ReportMonth>({month:(initialMonth+1)%12+1,year:initialYear+Math.floor((initialMonth+1)/12)}),[feedback,setFeedback]=useState('');
 const years=Array.from(new Set([...yearsAvailable,initialYear-1,initialYear,initialYear+1,start.year,end.year])).sort((a,b)=>b-a);
 const field=(label:string,value:ReportMonth,setter:(value:ReportMonth)=>void)=><label><span className="label">{label}</span><div className="mt-1 flex gap-2"><select className="field" value={value.month} onChange={e=>setter({...value,month:Number(e.target.value)})}>{monthNames.map((name,index)=><option value={index+1} key={name}>{name}</option>)}</select><select className="field" value={value.year} onChange={e=>setter({...value,year:Number(e.target.value)})}>{years.map(value=><option key={value}>{value}</option>)}</select></div></label>;
 const apply=()=>{setFeedback('');if(mode==='single'){onApply(null);setFeedback('Data diperbarui.');return}if(mode==='quarterly'){const months=[0,1,2].map(offset=>({month:(quarter-1)*3+offset+1,year}));onApply({mode:'quarterly',months,label:`Q${quarter} ${year}`});setFeedback('Data diperbarui.');return}const months=customThreeMonthRange(start,end);if(!months){setFeedback('Periode Custom harus terdiri dari 3 bulan berturut-turut.');return}onApply({mode:'custom',months,label:`${monthNames[start.month-1]} ${start.year} - ${monthNames[end.month-1]} ${end.year}`});setFeedback('Data diperbarui.')};
 return <div className="no-print card flex flex-wrap items-end gap-3 p-4"><label><span className="label">Mode Laporan</span><select className="field mt-1 block" value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="single">Periode Tunggal</option><option value="quarterly">Quarterly</option><option value="custom">Custom 3 Bulan</option></select></label>{mode==='quarterly'&&<><label><span className="label">Tahun</span><select className="field mt-1 block" value={year} onChange={e=>setYear(Number(e.target.value))}>{years.map(value=><option key={value}>{value}</option>)}</select></label><label><span className="label">Quarter</span><select className="field mt-1 block" value={quarter} onChange={e=>setQuarter(Number(e.target.value) as 1|2|3|4)}>{[1,2,3,4].map(value=><option value={value} key={value}>Q{value}</option>)}</select></label></>}{mode==='custom'&&<>{field('Periode Awal',start,setStart)}{field('Periode Akhir',end,setEnd)}</>}<button className="btn" onClick={apply}><RefreshCw size={14}/> Refresh</button>{feedback&&<span className={feedback.startsWith('Periode')?'text-xs text-red-400':'text-xs text-emerald-400'}>{feedback}</span>}{mode!=='single'&&<span className="w-full text-[10px] text-blue-300">Dalam mode multi-periode, filter Bulan/Tahun global diabaikan; Company, Department, dan Cost Center tetap berlaku.</span>}</div>
}
function periodRows(transactions:FinancialTransaction[],filters:DashboardFilters,period:ReportMonth,type:FinancialTransaction['statement_type']){return applyFilters(transactions,{...filters,period:'all',month:String(period.month),year:String(period.year)}).filter(row=>row.statement_type===type)}
function accountMatrix(sources:FinancialTransaction[][]){const map=new Map<string,{code:string;name:string;values:number[]}>();sources.forEach((source,index)=>source.forEach(row=>{const key=`${row.account_code}|${row.account_name}`,item=map.get(key)||{code:row.account_code,name:row.account_name,values:[0,0,0]};item.values[index]=(item.values[index]||0)+transactionBalance(row);map.set(key,item)}));return Array.from(map.values()).sort((a,b)=>a.code.localeCompare(b.code,undefined,{numeric:true}))}
function MultiTable({title,months,sections}:{title:string;months:ReportMonth[];sections:{label:string;sources:FinancialTransaction[][];totals:number[]}[]}){return <div className="space-y-4"><div className="text-center"><h2 className="text-lg font-bold">{title}</h2></div><div className="card overflow-x-auto"><table className="quarter-table"><thead><tr><th>Akun</th>{months.map(period=><th className="text-right" key={`${period.year}-${period.month}`}>{monthNames[period.month-1].slice(0,3).toUpperCase()} {period.year}</th>)}</tr></thead><tbody>{sections.map(section=><FragmentSection key={section.label} section={section}/>)}</tbody></table></div></div>}
function FragmentSection({section}:{section:{label:string;sources:FinancialTransaction[][];totals:number[]}}){const accounts=accountMatrix(section.sources);return <><tr className="bg-[#101e30]"><th colSpan={4} className="text-sm font-bold text-slate-100">{section.label}</th></tr>{accounts.length?accounts.map(account=><tr key={`${account.code}|${account.name}`}><td><span className="font-mono text-slate-500">{account.code}</span><span className="ml-3 text-slate-200">{account.name}</span></td>{account.values.map((value,index)=><td className="text-right tabular-nums" key={index}>{money(value)}</td>)}</tr>):<tr><td colSpan={4} className="text-slate-500">Belum ada data pada bagian ini.</td></tr>}<tr className="bg-[#111f31] font-bold"><td>TOTAL {section.label}</td>{section.totals.map((value,index)=><td className="text-right tabular-nums" key={index}>{money(value)}</td>)}</tr></>}

export function NeracaReportWithPeriods(){const {transactions,filters}=useFinancial();const [selection,setSelection]=useState<Selection|null>(null);const statements=useMemo(()=>selection?selection.months.map(period=>calculateNeraca(periodRows(transactions,filters,period,'balance-sheet'))):[],[selection,transactions,filters]);return <div className="space-y-5"><PeriodControls onApply={setSelection}/>{!selection?<NeracaReport/>:<MultiTable title={`NERACA — ${selection.label}`} months={selection.months} sections={[{label:'ASET',sources:statements.map(item=>item.assets),totals:statements.map(item=>item.totalAssets)},{label:'LIABILITAS',sources:statements.map(item=>item.liabilities),totals:statements.map(item=>item.totalLiabilities)},{label:'EKUITAS',sources:statements.map(item=>item.equity),totals:statements.map(item=>item.totalEquity)}]}/>}</div>}
export function CashFlowReportWithPeriods(){const {transactions,filters}=useFinancial();const [selection,setSelection]=useState<Selection|null>(null);const statements=useMemo(()=>selection?selection.months.map(period=>calculateCashFlow(periodRows(transactions,filters,period,'cash-flow'))):[],[selection,transactions,filters]);if(!selection)return <div className="space-y-5"><PeriodControls onApply={setSelection}/><CashFlowReport/></div>;const first=statements[0],last=statements[statements.length-1],net=statements.reduce((sum,item)=>sum+item.netChange,0);return <div className="space-y-5"><PeriodControls onApply={setSelection}/><div className="grid gap-3 sm:grid-cols-3"><div className="card p-4"><span className="label">Opening Cash</span><b className="mt-2 block">{money(first?.openingBalance||0)}</b></div><div className="card p-4"><span className="label">Net Cash Flow</span><b className="mt-2 block">{money(net)}</b></div><div className="card p-4"><span className="label">Ending Cash</span><b className="mt-2 block">{money(last?.closingBalance||0)}</b></div></div><MultiTable title={`ARUS KAS — ${selection.label}`} months={selection.months} sections={[{label:'AKTIVITAS OPERASI',sources:statements.map(item=>item.operating),totals:statements.map(item=>item.operatingTotal)},{label:'AKTIVITAS INVESTASI',sources:statements.map(item=>item.investing),totals:statements.map(item=>item.investingTotal)},{label:'AKTIVITAS PENDANAAN',sources:statements.map(item=>item.financing),totals:statements.map(item=>item.financingTotal)}]}/></div>}
