'use client';
import {useMemo} from 'react';
import {applyFilters,useFinancial} from '@/lib/financial-store';
import type {FinancialTransaction} from '@/lib/schema';

const money=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
const balance=(r:FinancialTransaction)=>['liability','equity','revenue','payable'].includes(r.account_type)?r.credit-r.debit:r.debit-r.credit;
const total=(rows:FinancialTransaction[])=>rows.reduce((n,r)=>n+balance(r),0);
const clean=(s:string)=>s?.trim()||'Lain-lain';

function Rows({rows}:{rows:FinancialTransaction[]}){return <>{rows.map(r=><div key={r.id} className="grid grid-cols-[110px,1fr,180px] gap-4 border-b border-[#203047]/70 px-4 py-2.5 text-xs last:border-0"><span className="text-slate-500">{r.account_code}</span><span>{r.account_name}</span><span className="text-right tabular-nums">{money(balance(r))}</span></div>)}</>}
function Section({title,rows}:{title:string;rows:FinancialTransaction[]}){if(!rows.length)return null;const groups=Array.from(new Set(rows.map(r=>clean(r.report_category||r.description))));return <section className="overflow-hidden rounded-lg border border-[#203047]"><div className="bg-[#101e30] px-4 py-3 text-sm font-bold uppercase tracking-wide">{title}</div>{groups.map(group=>{const items=rows.filter(r=>clean(r.report_category||r.description)===group);return <div key={group}><div className="flex items-center justify-between border-y border-[#203047] bg-[#0b1726] px-4 py-2 text-xs font-semibold text-slate-300"><span>{group}</span><span>{money(total(items))}</span></div><Rows rows={items}/></div>})}<div className="flex items-center justify-between border-t border-[#2a3b53] bg-[#0b1726] px-4 py-3 text-sm font-bold"><span>Total {title}</span><span>{money(total(rows))}</span></div></section>}

export function NeracaReport(){const {transactions,filters}=useFinancial();const rows=useMemo(()=>applyFilters(transactions,filters).filter(r=>r.statement_type==='balance-sheet'),[transactions,filters]);const assets=rows.filter(r=>['asset','cash','receivable','inventory'].includes(r.account_type));const liabilities=rows.filter(r=>['liability','payable'].includes(r.account_type));const equity=rows.filter(r=>r.account_type==='equity');const aset=total(assets),pasiva=total(liabilities)+total(equity),difference=aset-pasiva;if(!rows.length)return <Empty report="Neraca"/>;return <div className="space-y-4"><div className="grid gap-3 md:grid-cols-3"><Summary label="Total Aset" value={aset}/><Summary label="Liabilitas + Ekuitas" value={pasiva}/><Summary label="Selisih" value={difference} note={Math.abs(difference)<1?'Neraca balance':'Perlu rekonsiliasi'}/></div><div className="grid gap-4 xl:grid-cols-2"><Section title="Aset" rows={assets}/><div className="space-y-4"><Section title="Liabilitas" rows={liabilities}/><Section title="Ekuitas" rows={equity}/><div className="flex items-center justify-between rounded-lg border border-[#2a3b53] bg-[#101e30] px-4 py-4 font-bold"><span>Total Liabilitas & Ekuitas</span><span>{money(pasiva)}</span></div></div></div></div>}

export function LabaRugiReport(){const {transactions,filters}=useFinancial();const rows=useMemo(()=>applyFilters(transactions,filters).filter(r=>r.statement_type==='income-statement'),[transactions,filters]);if(!rows.length)return <Empty report="Laba Rugi"/>;const revenue=rows.filter(r=>r.account_type==='revenue');const expenses=rows.filter(r=>r.account_type==='expense');const hpp=expenses.filter(r=>/hpp|harga pokok|cost of goods|cogs/i.test(`${r.report_category} ${r.account_name}`));const operating=expenses.filter(r=>!hpp.includes(r));const pendapatan=total(revenue),totalHpp=total(hpp),gross=pendapatan-totalHpp,totalExpense=total(operating),net=gross-totalExpense;return <div className="space-y-4"><div className="grid gap-3 md:grid-cols-4"><Summary label="Pendapatan" value={pendapatan}/><Summary label="Laba Kotor" value={gross}/><Summary label="Beban" value={totalHpp+totalExpense}/><Summary label="Laba Bersih" value={net}/></div><div className="mx-auto max-w-5xl overflow-hidden rounded-lg border border-[#203047]"><div className="bg-[#101e30] px-5 py-4"><h3 className="text-base font-bold">Laporan Laba Rugi</h3><p className="mt-1 text-xs text-slate-500">Pendapatan dikurangi HPP dan seluruh beban periode terpilih.</p></div><ReportLine label="PENDAPATAN" value={pendapatan} strong/><Rows rows={revenue}/><ReportLine label="Total Pendapatan" value={pendapatan} strong/><ReportLine label="HARGA POKOK PENJUALAN" value={totalHpp} strong/>{hpp.length?<Rows rows={hpp}/>:<Hint text="Tidak ada akun yang dikategorikan sebagai HPP."/>}<ReportLine label="LABA KOTOR" value={gross} strong accent/><ReportLine label="BEBAN OPERASIONAL & LAINNYA" value={totalExpense} strong/><Rows rows={operating}/><ReportLine label="Total Beban" value={totalHpp+totalExpense} strong/><ReportLine label="LABA BERSIH" value={net} strong accent/></div></div>}

function Summary({label,value,note}:{label:string;value:number;note?:string}){return <div className="card p-4"><div className="label">{label}</div><div className="mt-2 text-lg font-bold tabular-nums">{money(value)}</div>{note&&<div className={`mt-1 text-[10px] ${note==='Neraca balance'?'text-emerald-400':'text-amber-400'}`}>{note}</div>}</div>}
function ReportLine({label,value,strong=false,accent=false}:{label:string;value:number;strong?:boolean;accent?:boolean}){return <div className={`flex items-center justify-between border-t border-[#203047] px-5 py-3 text-sm ${strong?'font-bold':''} ${accent?'bg-blue-500/10 text-blue-100':'bg-[#0b1726]'}`}><span>{label}</span><span className="tabular-nums">{money(value)}</span></div>}
function Hint({text}:{text:string}){return <div className="border-t border-[#203047] px-5 py-3 text-xs text-slate-500">{text}</div>}
function Empty({report}:{report:string}){return <div className="card flex min-h-64 items-center justify-center p-8 text-center"><div><h3 className="font-semibold">Belum ada data {report}</h3><p className="mt-2 text-xs text-slate-500">Upload file {report} melalui tombol Upload File. Jurnal tidak diperlukan.</p></div></div>}
