'use client';

import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,Check,CloudUpload,FileSpreadsheet,X} from 'lucide-react';
import * as XLSX from 'xlsx';
import {useFinancial} from '@/lib/financial-store';
import {useRestaurant} from '@/lib/restaurant-client';
import {parseAccurateWorkbook,type AccurateImportResult} from '@/lib/accurate-import';
import type {AccountType,BudgetRecord,FinancialTransaction,ImportRecord,StatementType} from '@/lib/schema';

const steps=['Upload File','Validate','Preview','Mapping','Confirm Import','Save Data','Success'];
type Raw=Record<string,unknown>;
type ParsedRow={index:number;valid:boolean;code:string;name:string;category:string;type:AccountType;date:Date;dc:{debit:number;credit:number};budget:number;period:string;rowMonth:string;rowYear:string;rowCompany:string;department:string;costCenter:string;summaryKind?:'opening'|'closing'};

const get=(row:Raw,...keys:string[])=>{const found=Object.keys(row).find(key=>keys.includes(key.toLowerCase().trim()));return found?String(row[found]??''):''};
const number=(value:string)=>Number(value.replace(/[^0-9.-]/g,''))||0;
const monthNames=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];

function statementFromModule(module:string):StatementType|''{const value=module.toLowerCase();if(value==='neraca')return'balance-sheet';if(value==='laba rugi')return'income-statement';if(value==='arus kas')return'cash-flow';return''}
function statementLabel(type:StatementType){return type==='balance-sheet'?'Neraca':type==='income-statement'?'Laba Rugi':type==='cash-flow'?'Arus Kas':'Jurnal'}
function classify(type:StatementType,code:string,name:string,category:string):AccountType{const value=`${category} ${name}`.toLowerCase();if(type==='cash-flow')return'cash';if(type==='income-statement')return /pendapatan|revenue|income|sales|penjualan/.test(value)||code.startsWith('4')?'revenue':'expense';if(/kas|bank|cash/.test(value))return'cash';if(/piutang|receivable/.test(value))return'receivable';if(/persediaan|inventory/.test(value))return'inventory';if(/hutang usaha|utang usaha|account payable|payable/.test(value))return'payable';if(/liabil|kewajiban|hutang|utang|liability/.test(value)||code.startsWith('2'))return'liability';if(/ekuitas|modal|equity|laba ditahan|current earnings|dividen/.test(value)||code.startsWith('3'))return'equity';return'asset'}
function encodedAmount(type:AccountType,amount:number){const creditNormal=['liability','equity','revenue','payable'].includes(type);if(creditNormal)return amount>=0?{debit:0,credit:amount}:{debit:-amount,credit:0};return amount>=0?{debit:amount,credit:0}:{debit:0,credit:-amount}}
function cashAmount(amount:number){return amount>=0?{debit:amount,credit:0}:{debit:0,credit:-amount}}
function excelDate(value:string,fallback:Date){if(!value)return fallback;const serial=Number(value);if(Number.isFinite(serial)&&serial>20000&&serial<100000){const parsed=XLSX.SSF.parse_date_code(serial);if(parsed)return new Date(parsed.y,parsed.m-1,parsed.d)}const parsed=new Date(value);return Number.isNaN(parsed.getTime())?fallback:parsed}

export function UploadModal({open,onOpenChange,module}:{open:boolean;onOpenChange:(value:boolean)=>void;module:string}){
  const store=useFinancial();
  const {activeRestaurant}=useRestaurant();
  const isBudget=module.toLowerCase().includes('budget');
  const fixedType=statementFromModule(module);
  const [step,setStep]=useState(0),[selected,setSelected]=useState<File|null>(null),[rows,setRows]=useState<Raw[]>([]),[error,setError]=useState(''),[accurate,setAccurate]=useState<AccurateImportResult|null>(null);
  const [company,setCompany]=useState('PT Triple Egg'),[statementType,setStatementType]=useState<StatementType>(fixedType||'balance-sheet');
  const now=new Date();const [month,setMonth]=useState(now.getMonth()+1),[year,setYear]=useState(now.getFullYear());

  useEffect(()=>{if(!open){setStep(0);setSelected(null);setRows([]);setError('');setAccurate(null);setStatementType(fixedType||'balance-sheet')}},[open,fixedType]);

  const read=async(file:File)=>{
    setSelected(file);setError('');setAccurate(null);
    try{
      const workbook=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});
      if(!isBudget){
        const detected=parseAccurateWorkbook(workbook);
        if(detected){
          if(fixedType&&fixedType!==detected.statementType){setError(`File Accurate terdeteksi sebagai ${statementLabel(detected.statementType)}, bukan ${statementLabel(fixedType)}.`);return}
          setAccurate(detected);setRows([]);setStatementType(detected.statementType);setCompany(detected.company);setMonth(detected.month);setYear(detected.year);
          if(detected.restaurantSlug&&activeRestaurant&&detected.restaurantSlug!==activeRestaurant.slug)setError(`File Accurate terdeteksi untuk ${detected.company}, sedangkan restoran aktif adalah ${activeRestaurant.name}. Ganti restoran aktif sebelum menyimpan agar data tidak tercampur.`);
          return;
        }
      }
      const imported=XLSX.utils.sheet_to_json<Raw>(workbook.Sheets[workbook.SheetNames[0]],{defval:''});
      if(isBudget){const headers=Object.keys(imported[0]||{}).map(value=>value.toLowerCase().trim());const required=['periode','bulan','tahun','company','department','cost center','kode akun','nama akun','kategori','budget'];const missing=required.filter(column=>!headers.includes(column));if(missing.length){setRows(imported);setError(`Kolom wajib belum tersedia: ${missing.join(', ')}.`);return}}
      setRows(imported);
    }catch{setError('File tidak dapat dibaca. Pastikan format file valid.')}
  };

  const parsed=useMemo<ParsedRow[]>(()=>{
    if(accurate)return accurate.rows.map((row,index)=>({index,valid:true,code:`ACC-${String(index+1).padStart(4,'0')}`,name:row.name,category:row.category,type:row.accountType,date:accurate.reportDate,dc:statementType==='cash-flow'?cashAmount(row.amount):encodedAmount(row.accountType,row.amount),budget:0,period:accurate.period,rowMonth:String(accurate.month),rowYear:String(accurate.year),rowCompany:accurate.company,department:'Semua Department',costCenter:'Semua Cost Center',summaryKind:row.summaryKind}));
    return rows.map((row,index)=>{const isCashFlow=statementType==='cash-flow';const code=get(row,'kode akun','account code','account_code');const category=isCashFlow?get(row,'aktivitas','activity','kategori','category'):get(row,'kategori','category','tipe akun','account type','account_type');const name=isCashFlow?get(row,'keterangan','description','nama akun','account name','account_name'):get(row,'nama akun','account name','account_name');const type=classify(statementType,code,name,category);const rawAmount=get(row,'saldo','actual','amount','nilai');const cashIn=number(get(row,'kas masuk','cash in','cash_in','inflow'));const cashOut=number(get(row,'kas keluar','cash out','cash_out','outflow'));const hasAmount=isCashFlow?(get(row,'kas masuk','cash in','cash_in','inflow')!==''||get(row,'kas keluar','cash out','cash_out','outflow')!==''):rawAmount!==''||get(row,'debit')!==''||get(row,'credit','kredit')!=='';const fallback=new Date(year,month-1,1);const date=excelDate(get(row,'tanggal','date','periode','period','transaction_date'),fallback);const fromDC={debit:number(get(row,'debit')),credit:number(get(row,'credit','kredit'))};const amount=number(rawAmount);const dc=isCashFlow?{debit:cashIn,credit:cashOut}:rawAmount!==''?encodedAmount(type,amount):fromDC;const budgetName=get(row,'nama akun','account name','account_name'),budgetCode=get(row,'kode akun','account code','account_code'),budgetAmount=get(row,'budget','nilai budget','amount');return{index,valid:isBudget?!!budgetCode&&!!budgetName&&budgetAmount!=='':!!name&&hasAmount,code:isBudget?budgetCode:code,name:isBudget?budgetName:name,category:isBudget?get(row,'kategori','category'):category,type,date,dc,budget:number(budgetAmount),period:get(row,'periode','period'),rowMonth:get(row,'bulan','month'),rowYear:get(row,'tahun','year'),rowCompany:get(row,'company','perusahaan'),department:get(row,'department','departemen'),costCenter:get(row,'cost center','cost_center')}});
  },[accurate,rows,statementType,month,year,isBudget]);
  const valid=parsed.filter(row=>row.valid);

  const save=()=>{
    if(!selected||error)return;
    const id=crypto.randomUUID(),createdAt=new Date().toISOString();
    if(isBudget){const budgetRows:BudgetRecord[]=valid.map((row,index)=>{const parsedMonth=Number(row.rowMonth)||month,parsedYear=Number(row.rowYear)||year,period=row.period||`${parsedYear}-${String(parsedMonth).padStart(2,'0')}`;return{id:`${id}-${index}`,period,month:parsedMonth,year:parsedYear,company_id:row.rowCompany||company,department_id:row.department||'Semua Department',cost_center_id:row.costCenter||'Semua Cost Center',account_code:row.code,account_name:row.name,category:row.category||'Lain-lain',budget:row.budget,source_file_id:id,created_at:createdAt}});const ext=selected.name.split('.').pop()?.toLowerCase() as ImportRecord['file_type'],period=budgetRows[0]?.period||`${year}-${String(month).padStart(2,'0')}`,companyId=budgetRows[0]?.company_id||company;store.importBudget(budgetRows,{id,file_name:selected.name,original_file_name:selected.name,file_type:ext,file_size:selected.size,module:'Budget',company_id:companyId,period,year:budgetRows[0]?.year||year,status:'Success',uploaded_by:'Admin Finance',uploaded_at:createdAt,processed_at:createdAt,rows_imported:budgetRows.length,rows_failed:rows.length-valid.length});setStep(5);return}
    const transactions:FinancialTransaction[]=valid.map((row,index)=>({id:`${id}-${index}`,transaction_date:row.date.toISOString().slice(0,10),account_code:row.code||`AUTO-${index+1}`,account_name:row.name,account_type:row.type,debit:row.dc.debit,credit:row.dc.credit,company_id:company,department_id:'Semua Department',cost_center_id:'Semua Cost Center',period:`${year}-${String(month).padStart(2,'0')}`,month,year,description:row.summaryKind?`Cash Flow Summary - ${row.summaryKind}`:row.category,report_category:row.summaryKind?`Cash Flow Summary - ${row.summaryKind}`:row.category,statement_type:statementType,source_file_id:id,created_at:createdAt}));
    const ext=selected.name.split('.').pop()?.toLowerCase() as ImportRecord['file_type'];const moduleName=statementLabel(statementType);const file:ImportRecord={id,file_name:selected.name,original_file_name:selected.name,file_type:ext,file_size:selected.size,module:moduleName,company_id:company,period:`${year}-${String(month).padStart(2,'0')}`,year,status:'Success',uploaded_by:'Admin Finance',uploaded_at:createdAt,processed_at:createdAt,rows_imported:transactions.length,rows_failed:accurate?0:rows.length-valid.length,statement_type:statementType};store.importData(transactions,file);setStep(6)
  };
  const next=()=>{if(step===0&&!selected)return;if(isBudget&&step===3){setStep(4);setTimeout(save,300)}else if(step===4){setStep(5);setTimeout(save,300)}else setStep(current=>Math.min(6,current+1))};
  if(!open)return null;
  const label=isBudget?'Budget':statementLabel(statementType);const mappingDetail=accurate?`${accurate.reportName} terdeteksi otomatis. Header, periode, hierarki akun, subtotal, dan total Accurate sudah dipetakan tanpa menghitung subtotal dua kali.`:statementType==='balance-sheet'?'Kode Akun, Nama Akun, Kategori, dan Saldo dipetakan ke struktur Neraca.':statementType==='income-statement'?'Kode Akun, Nama Akun, Kategori, dan Actual dipetakan ke struktur Laba Rugi.':'Tanggal, Aktivitas, Keterangan, Kas Masuk, dan Kas Keluar dipetakan ke struktur Arus Kas.';

  return <><div className="fixed inset-0 z-[70] bg-black/70" onClick={()=>onOpenChange(false)}/><section role="dialog" aria-modal="true" className="fixed left-1/2 top-1/2 z-[71] max-h-[92vh] w-[94vw] max-w-3xl -translate-x-1/2 -translate-y-1/2 overflow-y-auto rounded-xl border border-[#2a3b53] bg-[#0d1928]"><header className="flex justify-between border-b border-[#203047] p-5"><div><h2 className="font-bold">Upload {isBudget?'Data':'Laporan'} — {label}</h2><p className="mt-1 text-xs text-slate-500">{isBudget?'Data akan divalidasi dan dipreview sebelum mengganti budget company + periode yang sama.':'Bisa upload template dashboard atau export Accurate langsung: Balance Sheet (Standard), Profit/Loss (Standard), dan Cash Flow (Direct).'}</p></div><button onClick={()=>onOpenChange(false)}><X size={18}/></button></header><div className="overflow-x-auto border-b border-[#203047] p-4"><div className="flex min-w-[600px]">{(isBudget?['Upload','Validate','Preview','Confirm','Save','Success']:steps).map((item,index)=><div className="flex flex-1 items-center gap-1 text-[9px]" key={item}><i className={`${index<=step?'bg-blue-600':'bg-[#203047]'} flex h-6 w-6 items-center justify-center rounded-full`}>{index<step?<Check size={11}/>:index+1}</i>{item}</div>)}</div></div><div className="p-5">
    {step===0&&<><div className="mb-4 grid gap-3 md:grid-cols-4">{!fixedType&&!accurate&&<label><span className="label">Jenis Laporan</span><select className="field mt-1 w-full" value={statementType} onChange={event=>setStatementType(event.target.value as StatementType)}><option value="balance-sheet">Neraca</option><option value="income-statement">Laba Rugi</option><option value="cash-flow">Arus Kas</option></select></label>}<label className={fixedType||accurate?'md:col-span-2':''}><span className="label">Company</span><input className="field mt-1 w-full" value={company} onChange={event=>setCompany(event.target.value)} readOnly={!!accurate}/></label><label><span className="label">Bulan</span><select className="field mt-1 w-full" value={month} onChange={event=>setMonth(Number(event.target.value))} disabled={!!accurate}>{monthNames.map((name,index)=><option key={name} value={index+1}>{name}</option>)}</select></label><label><span className="label">Tahun</span><input className="field mt-1 w-full" type="number" value={year} onChange={event=>setYear(Number(event.target.value))} readOnly={!!accurate}/></label></div><label className="flex min-h-44 cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-[#35506e] bg-[#0a1522]"><input type="file" accept=".xlsx,.xls,.csv" className="hidden" onChange={event=>event.target.files?.[0]&&read(event.target.files[0])}/>{selected?<><FileSpreadsheet className="mb-3 text-green-500"/><b>{selected.name}</b><small className="text-slate-500">{accurate?`${accurate.reportName} • ${valid.length} baris detail terbaca`:`${rows.length} baris terbaca`}</small></>:<><CloudUpload className="mb-3 text-blue-500"/><b>Pilih XLSX, XLS, atau CSV</b><span className="mt-2 text-xs text-slate-500">Export Accurate dapat diupload langsung tanpa mengubah format.</span></>}</label>{accurate&&!error&&<div className="mt-3 rounded-lg border border-emerald-500/30 bg-emerald-500/10 p-3 text-xs text-emerald-300"><b>Format Accurate terdeteksi otomatis.</b><div className="mt-1 text-emerald-200/80">{accurate.reportName} • {accurate.company} • {monthNames[accurate.month-1]} {accurate.year}</div></div>}{error&&<div className="mt-3 flex gap-2 rounded-lg border border-amber-500/30 bg-amber-500/10 p-3 text-xs text-amber-300"><AlertTriangle size={16} className="shrink-0"/><span>{error}</span></div>}</>}
    {step===1&&<State title="File valid" detail={accurate?`${accurate.reportName} dikenali. ${valid.length} baris detail siap diimport; subtotal/total Accurate tidak akan dihitung ganda.`:`${valid.length} dari ${rows.length} baris laporan siap diimport.`}/>} {step===2&&<><Preview rows={valid.slice(0,8)} cashFlow={!isBudget&&statementType==='cash-flow'} budget={isBudget}/>{accurate?.cashFlowSummary&&<CashFlowCheck summary={accurate.cashFlowSummary}/>}</>} {step===3&&<State title={isBudget?'Konfirmasi Import':'Mapping otomatis'} detail={isBudget?`${valid.length} baris Budget akan mengganti data lama untuk company dan periode yang sama.`:mappingDetail}/>} {step===4&&<State title={isBudget?'Menyimpan Budget':'Konfirmasi Import'} detail={isBudget?'Data tervalidasi sedang disimpan.':`${valid.length} baris ${label} akan disimpan untuk ${company} periode ${monthNames[month-1]} ${year}.`}/>} {step===5&&<State title={isBudget?'Import berhasil':'Menyimpan laporan'} detail={isBudget?`${valid.length} baris Budget tersimpan dan laporan telah diperbarui.`:'Dashboard dan laporan keuangan akan dihitung ulang otomatis.'}/>} {!isBudget&&step===6&&<State title="Import berhasil" detail={`${valid.length} baris ${label} tersimpan dan laporan telah diperbarui.`}/>}</div><footer className="flex justify-between border-t border-[#203047] p-4"><button className="btn" onClick={()=>onOpenChange(false)}>{step===(isBudget?5:6)?'Tutup':'Cancel'}</button>{step<(isBudget?4:5)&&<button className="btn btn-primary" disabled={!selected||!!error} onClick={next}>{step===(isBudget?3:4)?'Confirm Import':'Lanjutkan'}</button>}</footer></section></>;
}

function State({title,detail}:{title:string;detail:string}){return <div className="py-12 text-center"><Check className="mx-auto mb-4 text-green-500"/><b>{title}</b><p className="mt-2 text-xs text-slate-500">{detail}</p></div>}
function Preview({rows,cashFlow=false,budget=false}:{rows:Array<{code:string;name:string;category:string;dc:{debit:number;credit:number};budget:number}>;cashFlow?:boolean;budget?:boolean}){return <div><b>Preview Data</b><div className="mt-3 overflow-x-auto rounded-lg border border-[#203047]"><table><thead><tr>{!cashFlow&&<th>Kode Akun</th>}<th>{cashFlow?'Keterangan':'Nama Akun'}</th><th>{cashFlow?'Aktivitas':'Kategori'}</th><th>{budget?'Budget':cashFlow?'Kas Masuk':'Debit'}</th>{!budget&&<th>{cashFlow?'Kas Keluar':'Credit'}</th>}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{!cashFlow&&<td>{row.code||'-'}</td>}<td>{row.name}</td><td>{row.category||'-'}</td><td>{(budget?row.budget:row.dc.debit).toLocaleString('id-ID')}</td>{!budget&&<td>{row.dc.credit.toLocaleString('id-ID')}</td>}</tr>)}</tbody></table></div></div>}
function CashFlowCheck({summary}:{summary:{opening?:number;closing?:number;netChange?:number;operating?:number;investing?:number;financing?:number}}){const opening=summary.opening??0,net=summary.netChange??0,closing=summary.closing??0,ok=Math.abs(opening+net-closing)<1;return <div className={`mt-4 rounded-lg border p-3 text-xs ${ok?'border-emerald-500/30 bg-emerald-500/10 text-emerald-300':'border-amber-500/30 bg-amber-500/10 text-amber-300'}`}><b>Validasi Cash Flow Accurate: {ok?'Balance ✓':'Perlu dicek'}</b><div className="mt-2 grid grid-cols-3 gap-3"><span>Opening<br/><b>Rp {opening.toLocaleString('id-ID')}</b></span><span>Net Change<br/><b>Rp {net.toLocaleString('id-ID')}</b></span><span>Ending<br/><b>Rp {closing.toLocaleString('id-ID')}</b></span></div></div>}
