'use client';

import * as XLSX from 'xlsx';
import {calculateCashFlow,calculateLabaRugi,calculateNeraca,reportCategory,transactionBalance} from './financial-report-data';
import type {DashboardFilters,FinancialTransaction} from './schema';
import {excelFilename} from './excel-export';

const rupiah='[$Rp-421] #,##0;[Red]-[$Rp-421] #,##0';
const excelDate=(value:string)=>value?new Date(`${value}T00:00:00`):'';
const border={top:{style:'thin',color:{rgb:'AAB7C4'}},bottom:{style:'thin',color:{rgb:'AAB7C4'}},left:{style:'thin',color:{rgb:'AAB7C4'}},right:{style:'thin',color:{rgb:'AAB7C4'}}};
const titleStyle={font:{bold:true,sz:16,color:{rgb:'FFFFFF'}},fill:{patternType:'solid',fgColor:{rgb:'17365D'}},alignment:{horizontal:'center'}};
const sectionStyle={font:{bold:true,color:{rgb:'FFFFFF'}},fill:{patternType:'solid',fgColor:{rgb:'1F4E78'}},border};
const categoryStyle={font:{bold:true},fill:{patternType:'solid',fgColor:{rgb:'D9EAF7'}},border};
const totalStyle={font:{bold:true},fill:{patternType:'solid',fgColor:{rgb:'DDEBF7'}},border};
type Row=(string|number|Date)[];
type Group=ReturnType<typeof import('./financial-report-data').groupedTransactions>[number];

function metadata(filters:DashboardFilters):Row[]{const value=(x:string,all:string)=>x==='all'?all:x;return [['Periode',value(filters.period,'Semua Periode')],['Bulan',value(filters.month,'Semua Bulan')],['Tahun',value(filters.year,'Semua Tahun')],['Company',value(filters.company_id,'Semua Company')],['Department',value(filters.department_id,'Semua Department')],['Cost Center',value(filters.cost_center_id,'Semua Cost Center')]]}
function styleRow(ws:XLSX.WorkSheet,row:number,from:number,to:number,style:object){for(let col=from;col<=to;col++){const cell=ws[XLSX.utils.encode_cell({r:row,c:col})];if(cell)cell.s=style}}
function finalize(ws:XLSX.WorkSheet,rows:Row[],widths:number[],titleEnd:number){ws['!cols']=widths.map(wch=>({wch}));ws['!merges']=[XLSX.utils.decode_range(`A1:${XLSX.utils.encode_col(titleEnd)}1`)];styleRow(ws,0,0,titleEnd,titleStyle);rows.forEach((row,r)=>row.forEach((_,c)=>{const cell=ws[XLSX.utils.encode_cell({r,c})];if(cell&&typeof cell.v==='number')cell.z=rupiah}));ws['!freeze']={xSplit:0,ySplit:9,topLeftCell:'A10',activePane:'bottomLeft',state:'frozen'}}
function addGroups(target:Row[],groups:Group[],section:string,totalLabel:string){target.push([section]);for(const group of groups){target.push([group.category]);for(const account of group.accounts)target.push([account.account_code,account.account_name,transactionBalance(account)]);target.push(['',`Subtotal ${group.category}`,group.total])}target.push(['',totalLabel,groups.reduce((sum,g)=>sum+g.total,0)])}
function applyVerticalStyles(ws:XLSX.WorkSheet,rows:Row[]){rows.forEach((row,index)=>{const first=String(row[0]??''),second=String(row[1]??'');if(first&&row.length===1)styleRow(ws,index,0,2,sectionStyle);else if(first&&!row[1]&&row.length===1)styleRow(ws,index,0,2,sectionStyle);else if(row.length===1)styleRow(ws,index,0,2,categoryStyle);if(/^(Subtotal|TOTAL|LABA|SALDO|KENAIKAN|STATUS)/i.test(second)||/^(TOTAL|LABA|SALDO|KENAIKAN|STATUS)/i.test(first))styleRow(ws,index,0,2,totalStyle)})}

function neracaSheet(rows:FinancialTransaction[],filters:DashboardFilters){const data=calculateNeraca(rows),left:Row[]=[],right:Row[]=[];addGroups(left,data.assetGroups,'ASET','TOTAL ASET');addGroups(right,data.liabilityGroups,'LIABILITAS','TOTAL LIABILITAS');addGroups(right,data.equityGroups,'EKUITAS','TOTAL EKUITAS');right.push(['','TOTAL LIABILITAS & EKUITAS',data.liabilitiesAndEquity],['','STATUS NERACA',data.balanced?'BALANCE':`SELISIH ${data.difference}`]);const output:Row[]=[['LAPORAN POSISI KEUANGAN'],...metadata(filters),[],['Kode Akun','Nama Akun','Saldo','','Kode Akun','Nama Akun','Saldo']];for(let i=0;i<Math.max(left.length,right.length);i++)output.push([...(left[i]||[]),'',...(right[i]||[])]);const ws=XLSX.utils.aoa_to_sheet(output,{cellDates:true});finalize(ws,output,[15,32,18,3,15,32,18],6);styleRow(ws,8,0,6,categoryStyle);output.forEach((_,i)=>{if(i<9)return;const l=left[i-9],r=right[i-9];if(l?.length===1)styleRow(ws,i,0,2,sectionStyle);else if(l&&(/Subtotal|TOTAL/.test(String(l[1]))))styleRow(ws,i,0,2,totalStyle);else if(l?.length===1)styleRow(ws,i,0,2,categoryStyle);if(r?.length===1)styleRow(ws,i,4,6,sectionStyle);else if(r&&(/Subtotal|TOTAL|STATUS/.test(String(r[1]))))styleRow(ws,i,4,6,totalStyle)});return ws}
function labaRugiSheet(rows:FinancialTransaction[],filters:DashboardFilters){const d=calculateLabaRugi(rows),output:Row[]=[['LAPORAN LABA RUGI'],...metadata(filters),[],['Kode Akun','Nama Akun','Nilai']];addGroups(output,d.revenueGroups,'PENDAPATAN','TOTAL PENDAPATAN');addGroups(output,d.hppGroups,'HARGA POKOK PENJUALAN (HPP)','TOTAL HPP');output.push(['','LABA KOTOR',d.grossProfit]);addGroups(output,d.operatingGroups,'BEBAN OPERASIONAL','TOTAL BEBAN OPERASIONAL');addGroups(output,d.nonOperatingGroups,'BEBAN LAIN-LAIN','TOTAL BEBAN LAIN-LAIN');output.push(['','TOTAL BEBAN',d.totalExpense],['','LABA BERSIH',d.netProfit],[],['SUMMARY'],['','Pendapatan',d.totalRevenue],['','HPP',d.totalHpp],['','Laba Kotor',d.grossProfit],['','Total Beban',d.totalExpense],['','Laba Bersih',d.netProfit],['','Gross Margin',d.grossMargin],['','Net Profit Margin',d.netMargin]);const ws=XLSX.utils.aoa_to_sheet(output,{cellDates:true});finalize(ws,output,[16,38,20],2);applyVerticalStyles(ws,output);for(const label of ['Gross Margin','Net Profit Margin']){const r=output.findIndex(row=>row[1]===label),cell=ws[XLSX.utils.encode_cell({r,c:2})];if(cell)cell.z='0.00"%"'}return ws}
function cashFlowSheet(rows:FinancialTransaction[],filters:DashboardFilters){const d=calculateCashFlow(rows),output:Row[]=[['LAPORAN ARUS KAS'],...metadata(filters),[],['Tanggal','Keterangan','Nilai']];const add=(label:string,items:FinancialTransaction[],subtotal:string)=>{output.push([label]);items.forEach(row=>output.push([excelDate(row.transaction_date),row.account_name,transactionBalance(row)]));output.push(['',subtotal,items.reduce((sum,row)=>sum+transactionBalance(row),0)])};add('ARUS KAS DARI AKTIVITAS OPERASI',d.operating,'ARUS KAS BERSIH DARI AKTIVITAS OPERASI');add('ARUS KAS DARI AKTIVITAS INVESTASI',d.investing,'ARUS KAS BERSIH DARI AKTIVITAS INVESTASI');add('ARUS KAS DARI AKTIVITAS PENDANAAN',d.financing,'ARUS KAS BERSIH DARI AKTIVITAS PENDANAAN');if(d.other.length)add('AKTIVITAS LAINNYA',d.other,'ARUS KAS BERSIH AKTIVITAS LAINNYA');output.push(['','SALDO KAS AWAL PERIODE',d.openingBalance],['','KENAIKAN / (PENURUNAN) BERSIH KAS',d.netChange],['','SALDO KAS AKHIR PERIODE',d.closingBalance]);const ws=XLSX.utils.aoa_to_sheet(output,{cellDates:true});finalize(ws,output,[16,48,22],2);applyVerticalStyles(ws,output);for(let r=9;r<output.length;r++){const cell=ws[XLSX.utils.encode_cell({r,c:0})];if(cell?.t==='d')cell.z='yyyy-mm-dd'}return ws}
function rawSheet(rows:FinancialTransaction[]){const data=[['Tanggal','Kode Akun','Nama Akun','Kategori','Debit','Credit','Saldo','Company','Department','Cost Center','Periode'],...rows.map(row=>[excelDate(row.transaction_date),row.account_code,row.account_name,reportCategory(row),row.debit,row.credit,transactionBalance(row),row.company_id,row.department_id,row.cost_center_id,row.period])];const ws=XLSX.utils.aoa_to_sheet(data,{cellDates:true});ws['!cols']=[14,14,30,24,18,18,18,20,20,20,14].map(wch=>({wch}));styleRow(ws,0,0,10,sectionStyle);for(let r=1;r<data.length;r++){const date=ws[XLSX.utils.encode_cell({r,c:0})];if(date)date.z='yyyy-mm-dd';for(const c of [4,5,6]){const cell=ws[XLSX.utils.encode_cell({r,c})];if(cell)cell.z=rupiah}}ws['!autofilter']={ref:`A1:K${Math.max(data.length,2)}`};return ws}

export function buildFinancialReportWorkbook(type:'neraca'|'laba-rugi'|'arus-kas',rows:FinancialTransaction[],filters:DashboardFilters){const workbook=XLSX.utils.book_new(),name=type==='neraca'?'Neraca':type==='laba-rugi'?'Laba Rugi':'Arus Kas';const report=type==='neraca'?neracaSheet(rows,filters):type==='laba-rugi'?labaRugiSheet(rows,filters):cashFlowSheet(rows,filters);XLSX.utils.book_append_sheet(workbook,report,name);XLSX.utils.book_append_sheet(workbook,rawSheet(rows),'Raw Data');return workbook}
export function downloadFinancialReport(type:'neraca'|'laba-rugi'|'arus-kas',rows:FinancialTransaction[],filters:DashboardFilters,title:string){XLSX.writeFile(buildFinancialReportWorkbook(type,rows,filters),excelFilename(title,filters.period,filters.company_id),{compression:true,cellStyles:true})}
