'use client';

import ExcelJS from 'exceljs';
import {calculateCashFlow,calculateDashboard,calculateLabaRugi,calculateNeraca,reportCategory,transactionBalance} from './financial-report-data';
import type {DashboardFilters,FinancialTransaction} from './schema';

export type RestaurantBrand={slug:'triple-egg'|'wok-this-way';name:'Triple Egg'|'Wok This Way';logoPath:string};
export const restaurantBrand=(company?:string):RestaurantBrand=>/wok\s*[- ]?this\s*[- ]?way/i.test(company||'')?{slug:'wok-this-way',name:'Wok This Way',logoPath:'/wok-this-way-logo.svg'}:{slug:'triple-egg',name:'Triple Egg',logoPath:'/triple-egg-logo.svg'};
export const belongsToRestaurant=(company:string,brand:RestaurantBrand)=>brand.slug==='wok-this-way'?/wok\s*[- ]?this\s*[- ]?way/i.test(company):!/wok\s*[- ]?this\s*[- ]?way/i.test(company);

const C={navy:'17365D',blue:'1F4E78',light:'D9EAF7',neutral:'F3F6F9',slate:'64748B',green:'D9EAD3',greenText:'18734A',red:'FCE8E6',redText:'B91C1C',white:'FFFFFF'};
const money='[$Rp-421] #,##0;[Red]-[$Rp-421] #,##0';
const thin={style:'thin' as const,color:{argb:'FFD7DEE7'}};
const value=(x:string,all:string)=>x==='all'?all:x;
const safe=(x:string)=>x.normalize('NFKD').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'');

async function logoPng(path:string){const response=await fetch(path);if(!response.ok)throw new Error('Logo restoran tidak dapat dimuat.');const svg=await response.text(),url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));try{return await new Promise<string>((resolve,reject)=>{const image=new Image();image.onload=()=>{const scale=Math.min(1,420/image.width),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d')?.drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/png').split(',')[1])};image.onerror=()=>reject(new Error('Logo restoran tidak dapat diproses.'));image.src=url})}finally{URL.revokeObjectURL(url)}}

function setup(sheet:ExcelJS.Worksheet,columns:number,headerRow:number){sheet.views=[{showGridLines:false,state:'frozen',ySplit:headerRow,activeCell:`A${headerRow+1}`}];sheet.pageSetup={orientation:'landscape',paperSize:9,fitToPage:true,fitToWidth:1,fitToHeight:0,margins:{left:.3,right:.3,top:.5,bottom:.5,header:.2,footer:.2},printTitlesRow:`1:${headerRow}`};sheet.headerFooter.oddFooter='&LGenerated from Restaurant Financial & Accounting Dashboard&RGenerated at: &D &T';sheet.properties.defaultRowHeight=20;sheet.getRow(1).height=52;sheet.mergeCells(1,1,1,columns);sheet.getCell(1,1).alignment={horizontal:'center',vertical:'middle'};sheet.getCell(1,1).font={bold:true,size:11,color:{argb:`FF${C.slate}`}}}
function header(sheet:ExcelJS.Worksheet,title:string,filters:DashboardFilters,brand:RestaurantBrand,columns:number,logoId?:number){setup(sheet,columns,9);if(logoId!==undefined)sheet.addImage(logoId,{tl:{col:.15,row:.15},ext:{width:112,height:brand.slug==='triple-egg'?38.7:40},editAs:'oneCell'});sheet.getCell('A1').value=`FINANCIAL & ACCOUNTING  •  ${brand.name.toUpperCase()}`;sheet.mergeCells(2,1,2,columns);const titleCell=sheet.getCell(2,1);titleCell.value=title;titleCell.font={bold:true,size:20,color:{argb:`FF${C.navy}`}};titleCell.alignment={horizontal:'center',vertical:'middle'};sheet.getRow(2).height=30;const meta=[['Periode',value(filters.period,'Semua Periode')],['Bulan',value(filters.month,'Semua Bulan')],['Tahun',value(filters.year,'Semua Tahun')],['Company',value(filters.company_id,brand.name)],['Department',value(filters.department_id,'Semua Department')],['Cost Center',value(filters.cost_center_id,'Semua Cost Center')]];meta.forEach(([label,text],i)=>{const row=4+Math.floor(i/3),col=1+(i%3)*Math.max(2,Math.floor(columns/3));sheet.getCell(row,col).value=`${label}:`;sheet.getCell(row,col).font={bold:true,color:{argb:`FF${C.slate}`},size:10};sheet.getCell(row,col+1).value=text;sheet.getCell(row,col+1).font={color:{argb:`FF${C.slate}`},size:10}})}
function styleColumns(row:ExcelJS.Row,ranges:Array<[number,number]>){ranges.forEach(([start,end])=>{for(let c=start;c<=end;c++){const cell=row.getCell(c);cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:`FF${C.blue}`}};cell.font={bold:true,color:{argb:`FF${C.white}`}};cell.alignment={vertical:'middle',horizontal:c===end?'right':'left'};cell.border={bottom:thin}}});row.height=24}
function styleCategory(row:ExcelJS.Row,start:number,end:number){for(let c=start;c<=end;c++){const cell=row.getCell(c);cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:`FF${C.light}`}};cell.font={bold:true,color:{argb:`FF${C.navy}`}};cell.alignment={vertical:'middle',wrapText:true};cell.border={bottom:thin}}row.height=22}
function styleSubtotal(row:ExcelJS.Row,start:number,end:number){for(let c=start;c<=end;c++){const cell=row.getCell(c);cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:`FF${C.neutral}`}};cell.font={bold:true,color:{argb:`FF${C.navy}`}};cell.border={top:thin};cell.alignment={vertical:'middle',horizontal:c===end?'right':'left'}}}
function styleTotal(row:ExcelJS.Row,start:number,end:number,accent=false,negative=false){for(let c=start;c<=end;c++){const cell=row.getCell(c);cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:`FF${accent?(negative?C.red:C.green):C.light}`}};cell.font={bold:true,size:12,color:{argb:`FF${negative?C.redText:(accent?C.greenText:C.navy)}`}};cell.border={top:{style:'medium',color:{argb:`FF${C.blue}`}},bottom:{style:'medium',color:{argb:`FF${C.blue}`}}};cell.alignment={vertical:'middle',horizontal:c===end?'right':'left'}}row.height=24}
function detail(row:ExcelJS.Row,start:number,end:number){row.height=20;for(let c=start;c<=end;c++){const cell=row.getCell(c);cell.alignment={vertical:'middle',horizontal:c===end?'right':'left',wrapText:c!==start};cell.border={bottom:{style:'hair',color:{argb:'FFE9EEF3'}}};if(c===end){cell.numFmt=money;if(typeof cell.value==='number'&&cell.value<0)cell.font={color:{argb:`FF${C.redText}`}}}}}
function addGroups(sheet:ExcelJS.Worksheet,start:number,groups:ReturnType<typeof import('./financial-report-data').groupedTransactions>,section:string,totalLabel:string){let row=sheet.addRow([]);row.getCell(start).value=section;styleColumns(row,[[start,start+2]]);for(const group of groups){row=sheet.addRow([]);row.getCell(start).value=group.category.toUpperCase();styleCategory(row,start,start+2);for(const account of group.accounts){row=sheet.addRow([]);row.getCell(start).value=account.account_code;row.getCell(start+1).value=account.account_name;row.getCell(start+2).value=transactionBalance(account);detail(row,start,start+2)}row=sheet.addRow([]);row.getCell(start+1).value=`Subtotal ${group.category}`;row.getCell(start+2).value=group.total;row.getCell(start+2).numFmt=money;styleSubtotal(row,start,start+2)}row=sheet.addRow([]);row.getCell(start+1).value=totalLabel;row.getCell(start+2).value=groups.reduce((n,g)=>n+g.total,0);row.getCell(start+2).numFmt=money;styleTotal(row,start,start+2);return row.number}
function addVerticalGroups(sheet:ExcelJS.Worksheet,groups:ReturnType<typeof import('./financial-report-data').groupedTransactions>,section:string,totalLabel:string){return addGroups(sheet,1,groups,section,totalLabel)}

function neraca(workbook:ExcelJS.Workbook,rows:FinancialTransaction[],filters:DashboardFilters,brand:RestaurantBrand,logoId?:number){const d=calculateNeraca(rows),sheet=workbook.addWorksheet('Neraca');header(sheet,'LAPORAN POSISI KEUANGAN',filters,brand,7,logoId);sheet.columns=[{width:15},{width:38},{width:20},{width:3},{width:15},{width:38},{width:20}];const head=sheet.getRow(9);['Kode Akun','Nama Akun','Saldo','','Kode Akun','Nama Akun','Saldo'].forEach((v,i)=>head.getCell(i+1).value=v);styleColumns(head,[[1,3],[5,7]]);const rightRows:unknown[][]=[];const temporary=workbook.addWorksheet('_neraca_right');addGroups(temporary,1,d.liabilityGroups,'LIABILITAS','TOTAL LIABILITAS');addGroups(temporary,1,d.equityGroups,'EKUITAS','TOTAL EKUITAS');let r=temporary.addRow(['','TOTAL LIABILITAS & EKUITAS',d.liabilitiesAndEquity]);r.getCell(3).numFmt=money;styleTotal(r,1,3);r=temporary.addRow(['',d.balanced?'NERACA BALANCE':'NERACA TIDAK BALANCE',d.balanced?null:d.difference]);r.getCell(3).numFmt=money;styleTotal(r,1,3,true,!d.balanced);temporary.eachRow(row=>rightRows.push(row.values as unknown[]));workbook.removeWorksheet(temporary.id);const leftData:unknown[][]=[];const leftTemp=workbook.addWorksheet('_neraca_left');addGroups(leftTemp,1,d.assetGroups,'ASET','TOTAL ASET');leftTemp.eachRow(row=>leftData.push(row.values as unknown[]));workbook.removeWorksheet(leftTemp.id);for(let i=0;i<Math.max(leftData.length,rightRows.length);i++){const row=sheet.addRow([]),l=leftData[i]||[],rr=rightRows[i]||[];for(let c=1;c<=3;c++){row.getCell(c).value=l[c] as ExcelJS.CellValue;row.getCell(c+4).value=rr[c] as ExcelJS.CellValue}const labelL=String(row.getCell(2).value||row.getCell(1).value||''),labelR=String(row.getCell(6).value||row.getCell(5).value||'');for(const [start,label] of [[1,labelL],[5,labelR]] as const){if(!label)continue;if(/^ASET$|^LIABILITAS$|^EKUITAS$/.test(label))styleColumns(row,[[start,start+2]]);else if(/^Subtotal/.test(label))styleSubtotal(row,start,start+2);else if(/^TOTAL/.test(label))styleTotal(row,start,start+2);else if(/^NERACA/.test(label))styleTotal(row,start,start+2,true,/TIDAK/.test(label));else if(!row.getCell(start+1).value)styleCategory(row,start,start+2);else detail(row,start,start+2);row.getCell(start+2).numFmt=money}}sheet.pageSetup.printArea=`A1:G${sheet.rowCount}`;return sheet}
function labaRugi(workbook:ExcelJS.Workbook,rows:FinancialTransaction[],filters:DashboardFilters,brand:RestaurantBrand,logoId?:number){const d=calculateLabaRugi(rows),sheet=workbook.addWorksheet('Laba Rugi');header(sheet,'LAPORAN LABA RUGI',filters,brand,3,logoId);sheet.columns=[{width:16},{width:42},{width:22}];const head=sheet.getRow(9);['Kode Akun','Nama Akun','Nilai'].forEach((v,i)=>head.getCell(i+1).value=v);styleColumns(head,[[1,3]]);addVerticalGroups(sheet,d.revenueGroups,'PENDAPATAN','TOTAL PENDAPATAN');addVerticalGroups(sheet,d.hppGroups,'HARGA POKOK PENJUALAN (HPP)','TOTAL HPP');let row=sheet.addRow(['','LABA KOTOR',d.grossProfit]);row.getCell(3).numFmt=money;styleTotal(row,1,3);addVerticalGroups(sheet,d.operatingGroups,'BEBAN OPERASIONAL','TOTAL BEBAN OPERASIONAL');addVerticalGroups(sheet,d.nonOperatingGroups,'BEBAN LAIN-LAIN','TOTAL BEBAN LAIN-LAIN');row=sheet.addRow(['','TOTAL BEBAN',d.totalExpense]);row.getCell(3).numFmt=money;styleTotal(row,1,3);row=sheet.addRow(['','LABA BERSIH',d.netProfit]);row.getCell(3).numFmt=money;styleTotal(row,1,3,true,d.netProfit<0);sheet.pageSetup.printArea=`A1:C${sheet.rowCount}`;return sheet}
function arusKas(workbook:ExcelJS.Workbook,rows:FinancialTransaction[],filters:DashboardFilters,brand:RestaurantBrand,logoId?:number){const d=calculateCashFlow(rows),sheet=workbook.addWorksheet('Arus Kas');header(sheet,'LAPORAN ARUS KAS',filters,brand,3,logoId);sheet.columns=[{width:16},{width:48},{width:22}];const head=sheet.getRow(9);['Tanggal','Keterangan','Nilai'].forEach((v,i)=>head.getCell(i+1).value=v);styleColumns(head,[[1,3]]);const add=(label:string,items:FinancialTransaction[],subtotal:string)=>{let row=sheet.addRow([label]);styleColumns(row,[[1,3]]);items.forEach(item=>{row=sheet.addRow([new Date(`${item.transaction_date}T00:00:00`),item.account_name,transactionBalance(item)]);row.getCell(1).numFmt='yyyy-mm-dd';detail(row,1,3)});row=sheet.addRow(['',subtotal,items.reduce((n,item)=>n+transactionBalance(item),0)]);row.getCell(3).numFmt=money;styleSubtotal(row,1,3)};add('ARUS KAS DARI AKTIVITAS OPERASI',d.operating,'ARUS KAS BERSIH DARI AKTIVITAS OPERASI');add('ARUS KAS DARI AKTIVITAS INVESTASI',d.investing,'ARUS KAS BERSIH DARI AKTIVITAS INVESTASI');add('ARUS KAS DARI AKTIVITAS PENDANAAN',d.financing,'ARUS KAS BERSIH DARI AKTIVITAS PENDANAAN');if(d.other.length)add('AKTIVITAS LAINNYA',d.other,'ARUS KAS BERSIH AKTIVITAS LAINNYA');for(const [label,amount,accent] of [['SALDO KAS AWAL PERIODE',d.openingBalance,false],['KENAIKAN / (PENURUNAN) BERSIH KAS',d.netChange,false],['SALDO KAS AKHIR PERIODE',d.closingBalance,true]] as const){const row=sheet.addRow(['',label,amount]);row.getCell(3).numFmt=money;styleTotal(row,1,3,accent,amount<0)}sheet.pageSetup.printArea=`A1:C${sheet.rowCount}`;return sheet}
function raw(workbook:ExcelJS.Workbook,rows:FinancialTransaction[]){const sheet=workbook.addWorksheet('Raw Data',{views:[{state:'frozen',ySplit:1}]});sheet.columns=[14,14,30,24,18,18,18,20,20,20,14].map(width=>({width}));const headers=['Tanggal','Kode Akun','Nama Akun','Kategori','Debit','Credit','Saldo','Company','Department','Cost Center','Periode'];sheet.addTable({name:'RawDataTable',ref:'A1',headerRow:true,style:{theme:'TableStyleMedium2',showRowStripes:true},columns:headers.map(name=>({name})),rows:rows.map(row=>[new Date(`${row.transaction_date}T00:00:00`),row.account_code,row.account_name,reportCategory(row),row.debit,row.credit,transactionBalance(row),row.company_id,row.department_id,row.cost_center_id,row.period])});sheet.getRow(1).height=24;for(let r=2;r<=sheet.rowCount;r++){sheet.getCell(r,1).numFmt='yyyy-mm-dd';for(const c of [5,6,7]){const cell=sheet.getCell(r,c);cell.numFmt=money;if(typeof cell.value==='number'&&cell.value<0)cell.font={color:{argb:`FF${C.redText}`}}}}return sheet}


function dashboard(workbook:ExcelJS.Workbook,rows:FinancialTransaction[],filters:DashboardFilters,brand:RestaurantBrand,logoId?:number){
  const data=calculateDashboard(rows),sheet=workbook.addWorksheet('Dashboard');header(sheet,'FINANCIAL & ACCOUNTING DASHBOARD',filters,brand,10,logoId);sheet.getCell('A3').value=`Ringkasan Kinerja Keuangan • Dashboard - ${brand.name}`;sheet.mergeCells('A3:J3');sheet.getCell('A3').font={italic:true,size:11,color:{argb:`FF${C.slate}`}};sheet.getCell('A3').alignment={horizontal:'center'};sheet.columns=Array.from({length:10},(_,index)=>({width:index%2===0?15:17}));
  const cards=[['TOTAL ASET',data.kpis.asset],['TOTAL LIABILITAS',data.kpis.liability],['TOTAL EKUITAS',data.kpis.equity],['PENDAPATAN',data.kpis.revenue],['BEBAN',data.kpis.expense],['LABA BERSIH',data.kpis.profit],['KAS & BANK',data.kpis.cash],['PIUTANG',data.kpis.receivable],['PERSEDIAAN',data.kpis.inventory],['HUTANG USAHA',data.kpis.payable]] as const;
  cards.forEach(([label,amount],index)=>{const group=index%5,start=group*2+1,top=8+Math.floor(index/5)*4;sheet.mergeCells(top,start,top,start+1);sheet.mergeCells(top+1,start,top+2,start+1);const labelCell=sheet.getCell(top,start),valueCell=sheet.getCell(top+1,start);labelCell.value=label;labelCell.font={bold:true,size:9,color:{argb:`FF${C.blue}`}};labelCell.fill={type:'pattern',pattern:'solid',fgColor:{argb:`FF${C.light}`}};labelCell.alignment={horizontal:'center',vertical:'middle'};valueCell.value=amount;valueCell.numFmt=money;valueCell.font={bold:true,size:15,color:{argb:`FF${amount<0?C.redText:C.navy}`}};valueCell.fill={type:'pattern',pattern:'solid',fgColor:{argb:`FF${C.neutral}`}};valueCell.alignment={horizontal:'center',vertical:'middle'};for(let r=top;r<=top+2;r++)for(let c=start;c<=start+1;c++)sheet.getCell(r,c).border={top:thin,bottom:thin,left:thin,right:thin};sheet.getRow(top+1).height=25});
  sheet.mergeCells('A16:J16');sheet.getCell('A16').value='ANALISA OTOMATIS';styleColumns(sheet.getRow(16),[[1,10]]);sheet.mergeCells('A17:J19');const insight=sheet.getCell('A17');insight.value=data.hasData?'Analisa dihitung dari laporan Neraca dan Laba Rugi yang sedang ditampilkan.':'Belum ada data yang cukup untuk analisa otomatis.';insight.alignment={vertical:'middle',horizontal:'left',wrapText:true};insight.font={size:11,color:{argb:`FF${C.slate}`}};insight.fill={type:'pattern',pattern:'solid',fgColor:{argb:`FF${C.neutral}`}};insight.border={top:thin,bottom:thin,left:thin,right:thin};
  sheet.mergeCells('A21:E21');sheet.getCell('A21').value='TREND PENDAPATAN VS BEBAN';sheet.mergeCells('G21:J21');sheet.getCell('G21').value='LABA BERSIH PER BULAN';styleColumns(sheet.getRow(21),[[1,5],[7,10]]);['Bulan','Pendapatan','Beban'].forEach((label,index)=>sheet.getCell(22,index+1).value=label);['Bulan','Laba Bersih'].forEach((label,index)=>sheet.getCell(22,index+7).value=label);styleCategory(sheet.getRow(22),1,3);styleCategory(sheet.getRow(22),7,8);
  if(data.monthly.length)data.monthly.forEach((item,index)=>{const row=23+index,month=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'][item.month-1];sheet.getCell(row,1).value=month;sheet.getCell(row,2).value=item.income;sheet.getCell(row,3).value=item.expense;sheet.getCell(row,7).value=month;sheet.getCell(row,8).value=item.profit;for(const c of [2,3,8]){const cell=sheet.getCell(row,c);cell.numFmt=money;cell.alignment={horizontal:'right'};if(typeof cell.value==='number'&&cell.value<0)cell.font={color:{argb:`FF${C.redText}`}}}if(index%2===1)for(const c of [1,2,3,7,8])sheet.getCell(row,c).fill={type:'pattern',pattern:'solid',fgColor:{argb:`FF${C.neutral}`}}});else{sheet.mergeCells('A23:E24');sheet.getCell('A23').value='Belum ada data trend untuk periode terpilih.';sheet.getCell('A23').alignment={horizontal:'center',vertical:'middle'};sheet.mergeCells('G23:J24');sheet.getCell('G23').value='Belum ada data laba bersih bulanan.';sheet.getCell('G23').alignment={horizontal:'center',vertical:'middle'}}
  sheet.pageSetup.printArea=`A1:J${Math.max(sheet.rowCount,24)}`;return sheet;
}

export async function buildDashboardWorkbook(rows:FinancialTransaction[],filters:DashboardFilters,brand=restaurantBrand(),logoBase64?:string){const workbook=new ExcelJS.Workbook();workbook.creator='Restaurant Financial & Accounting Dashboard';workbook.created=new Date();const logo=logoBase64?workbook.addImage({base64:`data:image/png;base64,${logoBase64}`,extension:'png'}):undefined;dashboard(workbook,rows,filters,brand,logo);raw(workbook,rows);return workbook}
export async function downloadDashboard(rows:FinancialTransaction[],filters:DashboardFilters,brand:RestaurantBrand){const logo=await logoPng(brand.logoPath),workbook=await buildDashboardWorkbook(rows,filters,brand,logo),buffer=await workbook.xlsx.writeBuffer(),url=URL.createObjectURL(new Blob([buffer],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})),link=document.createElement('a');link.href=url;link.download=`Dashboard-Keuangan_${safe(brand.name)}_${filters.period==='all'?'Semua-Periode':safe(filters.period)}.xlsx`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}
export async function buildFinancialReportWorkbook(type:'neraca'|'laba-rugi'|'arus-kas',rows:FinancialTransaction[],filters:DashboardFilters,brand=restaurantBrand(),logoBase64?:string){const workbook=new ExcelJS.Workbook();workbook.creator='Restaurant Financial & Accounting Dashboard';workbook.created=new Date();const logo=logoBase64?workbook.addImage({base64:`data:image/png;base64,${logoBase64}`,extension:'png'}):undefined;if(type==='neraca')neraca(workbook,rows,filters,brand,logo);else if(type==='laba-rugi')labaRugi(workbook,rows,filters,brand,logo);else arusKas(workbook,rows,filters,brand,logo);raw(workbook,rows);return workbook}
export async function downloadFinancialReport(type:'neraca'|'laba-rugi'|'arus-kas',rows:FinancialTransaction[],filters:DashboardFilters,title:string,brand:RestaurantBrand){const logo=await logoPng(brand.logoPath),workbook=await buildFinancialReportWorkbook(type,rows,filters,brand,logo),buffer=await workbook.xlsx.writeBuffer(),url=URL.createObjectURL(new Blob([buffer],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})),link=document.createElement('a');link.href=url;link.download=`${safe(brand.name)}_${safe(title)}_${filters.period==='all'?'Semua-Periode':safe(filters.period)}.xlsx`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}
