'use client';
import {createContext,useCallback,useContext,useEffect,useState} from 'react';
import type {AccountType,BudgetRecord,DashboardFilters,FinancialTransaction,ImportRecord} from './schema';

const TX_KEY='tripleegg.financial_transactions.v1', FILE_KEY='tripleegg.uploaded_files.v1', BUDGET_KEY='tripleegg.budgets.v1';
export const emptyFilters:DashboardFilters={period:'all',month:'all',year:'all',company_id:'all',department_id:'all',cost_center_id:'all',source_file_id:'all'};
const monthNames=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];
export {monthNames};
export const accountType=(value:string,name=''):AccountType=>{const v=`${value} ${name}`.toLowerCase();if(/kas|bank|cash/.test(v))return'cash';if(/piutang|receivable/.test(v))return'receivable';if(/persediaan|inventory/.test(v))return'inventory';if(/hutang usaha|account payable|payable/.test(v))return'payable';if(/aset|asset/.test(v))return'asset';if(/liabil|kewajiban|liability/.test(v))return'liability';if(/ekuitas|modal|equity/.test(v))return'equity';if(/pendapatan|revenue|income/.test(v))return'revenue';return'expense'};
type Store={transactions:FinancialTransaction[];budgets:BudgetRecord[];files:ImportRecord[];filters:DashboardFilters;setFilters:(v:DashboardFilters)=>void;importData:(t:FinancialTransaction[],f:ImportRecord)=>void;importBudget:(b:BudgetRecord[],f:ImportRecord)=>void;deleteFile:(id:string)=>void;deleteFiltered:(f:DashboardFilters)=>void;ready:boolean};
const Context=createContext<Store|null>(null);
export function FinancialProvider({children}:{children:React.ReactNode}){const [transactions,setTransactions]=useState<FinancialTransaction[]>([]),[budgets,setBudgets]=useState<BudgetRecord[]>([]),[files,setFiles]=useState<ImportRecord[]>([]),[filters,setFilters]=useState(emptyFilters),[ready,setReady]=useState(false);
 useEffect(()=>{try{setTransactions(JSON.parse(localStorage.getItem(TX_KEY)||'[]'));setBudgets(JSON.parse(localStorage.getItem(BUDGET_KEY)||'[]'));setFiles(JSON.parse(localStorage.getItem(FILE_KEY)||'[]'))}finally{setReady(true)}},[]);
 const save=useCallback((t:FinancialTransaction[],f:ImportRecord[],b=budgets)=>{setTransactions(t);setBudgets(b);setFiles(f);localStorage.setItem(TX_KEY,JSON.stringify(t));localStorage.setItem(BUDGET_KEY,JSON.stringify(b));localStorage.setItem(FILE_KEY,JSON.stringify(f))},[budgets]);
 const importData=(rows:FinancialTransaction[],file:ImportRecord)=>{if(file.statement_type&&file.statement_type!=='journal'){const replacedIds=new Set(files.filter(x=>x.statement_type===file.statement_type&&x.company_id===file.company_id&&x.period===file.period).map(x=>x.id));save([...transactions.filter(x=>!replacedIds.has(x.source_file_id)),...rows],[file,...files.filter(x=>!replacedIds.has(x.id))]);return}save([...transactions,...rows],[file,...files])};
 const importBudget=(rows:BudgetRecord[],file:ImportRecord)=>{const replacedIds=new Set(files.filter(x=>x.module==='Budget'&&x.company_id===file.company_id&&x.period===file.period).map(x=>x.id));save(transactions,[file,...files.filter(x=>!replacedIds.has(x.id))],[...budgets.filter(x=>!replacedIds.has(x.source_file_id)),...rows])};
 const deleteFile=(id:string)=>save(transactions.filter(x=>x.source_file_id!==id),files.filter(x=>x.id!==id),budgets.filter(x=>x.source_file_id!==id));
 const deleteFiltered=(f:DashboardFilters)=>{const matches=(x:FinancialTransaction)=>(f.company_id==='all'||x.company_id===f.company_id)&&(f.month==='all'||String(x.month)===f.month)&&(f.year==='all'||String(x.year)===f.year)&&(f.department_id==='all'||x.department_id===f.department_id)&&(f.cost_center_id==='all'||x.cost_center_id===f.cost_center_id)&&(f.source_file_id==='all'||x.source_file_id===f.source_file_id);const remaining=transactions.filter(x=>!matches(x));const ids=new Set(remaining.map(x=>x.source_file_id));save(remaining,files.filter(x=>ids.has(x.id)||transactions.some(t=>t.source_file_id===x.id&&!matches(t))))};
 return <Context.Provider value={{transactions,budgets,files,filters,setFilters,importData,importBudget,deleteFile,deleteFiltered,ready}}>{children}</Context.Provider>}
export function useFinancial(){const v=useContext(Context);if(!v)throw new Error('FinancialProvider is required');return v}
export function applyFilters<T extends {period:string;month:number;year:number;company_id:string;department_id:string;cost_center_id:string;source_file_id:string}>(rows:T[],f:DashboardFilters){return rows.filter(x=>(f.period==='all'||x.period===f.period)&&(f.month==='all'||String(x.month)===f.month)&&(f.year==='all'||String(x.year)===f.year)&&(f.company_id==='all'||x.company_id===f.company_id)&&(f.department_id==='all'||x.department_id===f.department_id)&&(f.cost_center_id==='all'||x.cost_center_id===f.cost_center_id)&&(f.source_file_id==='all'||x.source_file_id===f.source_file_id))}
